// GENERATED by aurora-mcp/scripts/sync-separation.mjs from aurora/src/shared/types/index.ts (the separation provider interfaces). Do not edit: edit the app's file
// and run `node scripts/sync-separation.mjs`. `--check` (in npm run typecheck) fails on drift.

/** A single MVSEP job spec (provider-agnostic; see mvsep-separation-contract.md A.4). */
export interface MvsepJobSpec {
  sep_type: string
  output_format: string
  is_demo: string
  add_opt1?: string
  add_opt2?: string
  add_opt3?: string
}

export interface SeparationResultFile {
  url: string
  /** MVSEP's suggested filename (`download`). */
  filename: string
  /** MVSEP's display label (`type`, "Drums", "Back instrum"): cross-checked against the filename's key. */
  label?: string
}

export interface SeparationResult {
  /** The algorithm MVSEP says produced the files; checked against the one asked for. */
  algorithm: string | null
  files: SeparationResultFile[]
}

/** A provider abstracts ONLY transport + auth. Orchestration (routes, output identity, hats/other
 *  phase-cancellation) lives in the desktop client ABOVE the provider. */
export interface SeparationProvider {
  /** `uploadName` must be unique per job: MVSEP's job hash is <create second>-<content hash>-<filename>,
   *  so two jobs uploading the same bytes under the same name in the same second share one result. */
  createJob(audio: Buffer, spec: MvsepJobSpec, uploadName: string): Promise<{ hash: string }>
  awaitResult(handle: { hash: string }, onPoll?: (status: string) => void): Promise<SeparationResult>
}
