// GENERATED by aurora-mcp/scripts/sync-separation.mjs from aurora/src/shared/separation/content-check.ts. Do not edit: edit the app's file
// and run `node scripts/sync-separation.mjs`. `--check` (in npm run typecheck) fails on drift.
// Does each downloaded stem hold what its name says? Checked from the audio itself, without the true stems:
// only the uploaded input and the returned files. Shared by the app and aurora-mcp (byte-identical copy).
//
// Three checks, calibrated on 49 real MVSEP jobs over clips mixed from true stems (2026-10-02; second-brain
// plans/2026-10-02-aurora-splitter-mvsep-research/tests/calibrate_identity.py):
// 1. Sums: outputs a route declares to add back to a whole must do so. Measured: one-model routes -148 to
//    -160 dB, ensembles -37 to -60 dB below the whole and -31 dB or more below their quietest part. A complement that still holds the target (an "instrumental" with the
//    vocal in it) counts the target twice and misses by roughly the target's own level.
// 2. Not the whole input: a target that equals the input while the rest of the result is not silent.
// 3. Family: a swapped label shows as a target that looks like what was left. Measured margins (target vs
//    rest): drums +3.9 to +12.9 dB more transient; bass +0.21 to +0.39 more energy under 150 Hz; vocals and
//    choir 0.46 to 0.79 less. Brass, strings, keys and the like have no cheap test and get checks 1 and 2.
import type { ContentFamily, SeparationRoute } from './routes.js'

export type Channels = Float32Array[]

export const CONTENT_THRESHOLDS = {
  /** A sum may miss its whole by at most this much (dB below the whole). Worst real job: -37 dB. */
  sumMaxDb: -20,
  /** ...and by at most this much below its quietest audible part, so a quiet target counted twice still
   *  shows (a bass at -29 dB mixed back into "other" misses the whole by only -29 dB). Worst real job: -31. */
  sumMaxBelowPartDb: -12,
  /** A target closer than this to the whole input (dB) "is" the input. */
  sameAsInputDb: -30,
  /** Below this level (dB under the input) a file is treated as silent: the group may not be in the track. */
  silentDb: -45,
  /** percussive: target transient measure minus the rest's, in dB. Smallest real margin +3.9. */
  percussiveMinDb: 1.5,
  /** low: target's share of energy under 150 Hz minus the rest's. Smallest real margin +0.21. */
  lowMinShare: 0.08,
  /** vocal: the rest's share under 150 Hz minus the target's. Smallest real margin +0.46. */
  vocalMinShare: 0.15
}

export interface ContentVerdict {
  ok: boolean
  /** Why the result cannot be trusted; empty when ok. */
  problems: string[]
  /** Things worth saying that are not failures (a near-silent group). */
  notes: string[]
  metrics: Record<string, number>
}

const energy = (chs: Channels): number => {
  let e = 0
  for (const c of chs) for (let i = 0; i < c.length; i++) e += c[i] * c[i]
  return e
}

const db = (num: number, den: number): number => 10 * Math.log10((num + 1e-20) / (den + 1e-20))

function combine(parts: Channels[], signs: number[]): Channels {
  const n = Math.min(...parts.map((p) => p[0]?.length ?? 0))
  const chCount = Math.min(...parts.map((p) => p.length))
  const out: Channels = []
  for (let ch = 0; ch < chCount; ch++) {
    const o = new Float32Array(n)
    parts.forEach((p, k) => {
      const src = p[ch]
      const s = signs[k]
      for (let i = 0; i < n; i++) o[i] += s * src[i]
    })
    out.push(o)
  }
  return out
}

function mono(chs: Channels): Float32Array {
  const n = chs[0]?.length ?? 0
  const m = new Float32Array(n)
  for (const c of chs) for (let i = 0; i < n; i++) m[i] += c[i] / chs.length
  return m
}

/** Share of energy under 150 Hz: a 4th-order Butterworth low-pass (two cascaded biquads), energy ratio. */
export function lowShare(chs: Channels, sampleRate: number): number {
  const x = mono(chs)
  const total = x.reduce((a, v) => a + v * v, 0)
  if (total < 1e-20) return 0
  const w0 = (2 * Math.PI * 150) / sampleRate
  let y: Float32Array = x
  for (const q of [0.5412, 1.3066]) {
    const alpha = Math.sin(w0) / (2 * q)
    const cos = Math.cos(w0)
    const a0 = 1 + alpha
    const b0 = (1 - cos) / 2 / a0
    const b1 = (1 - cos) / a0
    const b2 = b0
    const a1 = (-2 * cos) / a0
    const a2 = (1 - alpha) / a0
    const out = new Float32Array(y.length)
    let x1 = 0, x2 = 0, y1 = 0, y2 = 0
    for (let i = 0; i < y.length; i++) {
      const v = b0 * y[i] + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
      x2 = x1
      x1 = y[i]
      y2 = y1
      y1 = v
      out[i] = v
    }
    y = out
  }
  return y.reduce((a, v) => a + v * v, 0) / total
}

/** Transient measure: 95th over 50th percentile of 10 ms frame energies, in dB. */
export function spikiness(chs: Channels, sampleRate: number): number {
  const x = mono(chs)
  const n = Math.max(1, Math.round(sampleRate / 100))
  const frames = Math.floor(x.length / n)
  if (frames < 20) return 0
  const e = new Float64Array(frames)
  for (let f = 0; f < frames; f++) {
    let s = 1e-12
    for (let i = f * n; i < (f + 1) * n; i++) s += x[i] * x[i]
    e[f] = s
  }
  e.sort()
  return 10 * Math.log10(e[Math.floor(frames * 0.95)] / e[Math.floor(frames * 0.5)])
}

/** Energy per sample below this is digital silence: two silent signals match, they do not "differ by 0 dB". */
const SILENCE_PER_SAMPLE = 1e-14

const sampleCount = (chs: Channels): number => chs.reduce((n, c) => n + c.length, 0)

/** Reported for digital silence: a perfect match, kept finite so the measurement survives JSON. */
export const SILENCE_DB = -200

/** db(num, den) where digital silence on top reads as a perfect match (SILENCE_DB). */
function dbVs(num: number, den: number, samples: number): number {
  if (num <= SILENCE_PER_SAMPLE * samples) return SILENCE_DB
  return Math.max(SILENCE_DB, db(num, den))
}

/** True when every sample is a finite number (a NaN or Infinity poisons every measurement after it). */
export function allFinite(chs: Channels): boolean {
  for (const c of chs) for (let i = 0; i < c.length; i++) if (!Number.isFinite(c[i])) return false
  return true
}

/** The audio a check reads: the same span of the input and of every output. */
export interface CheckView {
  input: Channels
  outputs: Record<string, Channels>
}

/**
 * Check one finished job of `route`. `input` is exactly what was uploaded; `outputs` holds every returned
 * output the route names, keyed by output key; all share one sample rate and are sample-aligned (MVSEP's models
 * preserve length and timing). The family tests need contiguous audio (`input`, `outputs`: a stretch from the
 * middle of the track); the sums and the duplicate-input test run on `wholeTrack`, a view that spans the whole
 * track (frames sampled across its full length), so damage outside the middle stretch still shows. Without
 * `wholeTrack` both use the given audio.
 */
export function checkRouteContent(
  route: SeparationRoute,
  input: Channels,
  outputs: Record<string, Channels>,
  sampleRate: number,
  t = CONTENT_THRESHOLDS,
  wholeTrack: CheckView = { input, outputs }
): ContentVerdict {
  const problems: string[] = []
  const notes: string[] = []
  const metrics: Record<string, number> = {}
  const W = wholeTrack
  const eInW = energy(W.input)

  for (const [key, chs] of Object.entries(W.outputs)) {
    if (!allFinite(chs)) problems.push(`"${key}" contains samples that are not numbers (NaN or infinity)`)
  }

  for (const { parts, whole } of route.sums) {
    const have = parts.filter((p) => W.outputs[p])
    const wholeAudio = whole === 'input' ? W.input : W.outputs[whole]
    if (have.length !== parts.length || !wholeAudio) continue // an output the model did not return this time
    const resid = combine([wholeAudio, ...have.map((p) => W.outputs[p])], [1, ...have.map(() => -1)])
    const n = sampleCount(resid)
    const eResid = energy(resid)
    const off = dbVs(eResid, energy(wholeAudio), n)
    const audible = have.map((p) => energy(W.outputs[p])).filter((e) => db(e, eInW) >= t.silentDb)
    const offPart = audible.length ? dbVs(eResid, Math.min(...audible), n) : off
    metrics[`sum:${parts.join('+')}`] = off
    metrics[`sumVsQuietestPart:${parts.join('+')}`] = offPart
    if (off > t.sumMaxDb || offPart > t.sumMaxBelowPartDb) {
      problems.push(
        `${parts.join(' + ')} do not add back to ${whole === 'input' ? 'the input' : whole} (off by ${off.toFixed(1)} dB, ` +
          `${offPart.toFixed(1)} dB against the quietest part): a file holds part of another, or came from another job`
      )
    }
  }

  // Two returned files that are both the whole input: the separation did not happen, whatever the names say.
  if (eInW > SILENCE_PER_SAMPLE * sampleCount(W.input)) {
    const copies = Object.entries(W.outputs)
      .filter(([, chs]) => db(energy(combine([W.input, chs], [1, -1])), eInW) < t.sameAsInputDb)
      .map(([key]) => key)
    if (copies.length >= 2) problems.push(`${copies.map((k) => `"${k}"`).join(' and ')} are each the whole input`)
  }

  const { target, complement, family } = route.family
  const tgt = outputs[target]
  if (!tgt) return { ok: problems.length === 0, problems, notes, metrics }
  const eIn = energy(input)
  const rest = complement && outputs[complement] ? outputs[complement] : combine([input, tgt], [1, -1])
  const tLevel = dbVs(energy(tgt), eIn, sampleCount(tgt))
  const rLevel = dbVs(energy(rest), eIn, sampleCount(rest))
  metrics.targetLevelDb = tLevel
  metrics.restLevelDb = rLevel

  if (tLevel < t.silentDb) notes.push(`"${target}" is nearly silent here: this group may not be in the track`)
  if (tLevel >= t.silentDb && rLevel >= t.silentDb) {
    familyCheck(family, target, tgt, rest, sampleRate, t, problems, notes, metrics)
  }
  return { ok: problems.length === 0, problems, notes, metrics }
}

function familyCheck(
  family: ContentFamily,
  target: string,
  tgt: Channels,
  rest: Channels,
  sr: number,
  t: typeof CONTENT_THRESHOLDS,
  problems: string[],
  notes: string[],
  metrics: Record<string, number>
): void {
  if (family === 'percussive') {
    const d = spikiness(tgt, sr) - spikiness(rest, sr)
    metrics.transientMarginDb = d
    if (d < t.percussiveMinDb) problems.push(`"${target}" is not more transient than the rest (${d.toFixed(1)} dB): it does not sound like drums`)
  } else if (family === 'low') {
    const d = lowShare(tgt, sr) - lowShare(rest, sr)
    metrics.lowMargin = d
    if (d < t.lowMinShare) problems.push(`"${target}" holds no more low end than the rest (${d.toFixed(2)}): it does not sound like bass`)
  } else if (family === 'vocal') {
    const restLow = lowShare(rest, sr)
    const targetLow = lowShare(tgt, sr)
    const d = restLow - targetLow
    metrics.vocalMargin = d
    // Voices over music with no low end (a cappella, high strings only): neither side has low end to compare,
    // so say so instead of calling it a swap. A swap still shows: the "voice" file then holds the low end.
    if (Math.max(restLow, targetLow) < t.vocalMinShare) {
      notes.push(`neither "${target}" nor the rest has low end, so the voice test could not tell them apart`)
    } else if (d < t.vocalMinShare) {
      problems.push(`"${target}" carries as much low end as the rest (${d.toFixed(2)}): it does not sound like voices`)
    }
  }
}
