// GENERATED by aurora-mcp/scripts/sync-separation.mjs from aurora/src/shared/separation/identify.ts. Do not edit: edit the app's file
// and run `node scripts/sync-separation.mjs`. `--check` (in npm run typecheck) fails on drift.
// Which returned file is which stem: resolved by exact MVSEP output keys, never by substring or list order.
//
// MVSEP names a result file `<upload name>_<model>_mt_<option>_<key>.<ext>` and labels it with `type`
// ("Drums", "Back instrum"). Keys change with options (`other` vs `instrum`), some files keep other sources by
// design (`back-instrum` keeps the backing vocals), and one model can return two files with the same label
// (Mega 53: `strings` and `bowed_strings`, both "Strings"). So a file's key is the LONGEST key of the requested
// algorithm that ends its filename after an underscore, and its `type` label must name that key.
// Shared by the app and aurora-mcp (byte-identical copy).
import { MVSEP_ALGORITHMS } from './mvsep-catalog.generated.js'

export interface ReturnedFile {
  url: string
  /** MVSEP's suggested filename (`download`), else the URL's last segment. */
  filename: string
  /** MVSEP's display label (`type`), when the response carried one. */
  label?: string
}

export interface ResolvedOutputs {
  /** Output key → the one file holding it. */
  byKey: Record<string, ReturnedFile>
  /** Files whose name ends in no known key of this algorithm (reported, never used). */
  unrecognized: ReturnedFile[]
}

export class OutputIdentityError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'OutputIdentityError'
  }
}

const norm = (s: string): string => s.toLowerCase().replace(/[\s_-]+/g, ' ').trim()

function baseName(file: ReturnedFile): string {
  const name = file.filename || decodeURIComponent(file.url.split('?')[0].split('/').pop() ?? '')
  return name.replace(/\.[a-z0-9]+$/i, '').toLowerCase()
}

/** The output key a file holds, or null: the longest known key the filename ends with after `_`. */
export function outputKeyOf(file: ReturnedFile, knownKeys: string[]): string | null {
  const name = baseName(file)
  let best: string | null = null
  for (const key of knownKeys) {
    if (name.endsWith(`_${key.toLowerCase()}`) && (!best || key.length > best.length)) best = key
  }
  return best
}

/**
 * Map a finished job's files to the output keys a route takes. Throws OutputIdentityError when:
 * - the result names another algorithm than the one asked for (two jobs that share a job hash get one
 *   result; seen 2026-10-02),
 * - a wanted key has no file, or two files resolve to it,
 * - a file's `type` label disagrees with the key its filename carries.
 */
export function resolveOutputs(
  sepType: number,
  files: ReturnedFile[],
  wanted: string[],
  returnedAlgorithm?: string | null
): ResolvedOutputs {
  const algo = MVSEP_ALGORITHMS[sepType]
  if (!algo) throw new OutputIdentityError(`sep_type ${sepType} is not in the MVSEP catalog (rerun tools/gen-mvsep-catalog.ts)`)
  // Every real result names its algorithm; without it a wrong job with compatible keys could pass.
  if (!returnedAlgorithm?.trim()) {
    throw new OutputIdentityError(
      `MVSEP's result for sep_type ${sepType} does not say which algorithm produced it, so it cannot be verified. Nothing was saved.`
    )
  }
  if (norm(returnedAlgorithm) !== norm(algo.name)) {
    throw new OutputIdentityError(
      `MVSEP returned a result for "${returnedAlgorithm}", not the requested "${algo.name}" (sep_type ${sepType}). ` +
        'Two jobs probably shared one job hash; nothing was saved. Run it again.'
    )
  }
  const keys = Object.keys(algo.outputs)
  const byKey: Record<string, ReturnedFile> = {}
  const unrecognized: ReturnedFile[] = []
  const list = files.map((f) => f.filename || f.url).join(', ')
  for (const file of files) {
    const key = outputKeyOf(file, keys)
    if (!key) {
      unrecognized.push(file)
      continue
    }
    // Real labels are the catalog's display name or the key itself ("Hh" for `hh`, "Instrum" for `instrum`).
    if (file.label && norm(file.label) !== norm(algo.outputs[key]) && norm(file.label) !== norm(key)) {
      throw new OutputIdentityError(
        `MVSEP file ${file.filename} carries key "${key}" but is labelled "${file.label}" (expected "${algo.outputs[key]}"). Files: ${list}`
      )
    }
    if (byKey[key]) {
      throw new OutputIdentityError(`Two MVSEP files resolve to "${key}" (${byKey[key].filename}, ${file.filename}). Files: ${list}`)
    }
    byKey[key] = file
  }
  const missing = wanted.filter((k) => !byKey[k])
  if (missing.length > 0) {
    throw new OutputIdentityError(
      `MVSEP result for ${algo.name} has no ${missing.map((k) => `"${k}"`).join(', ')} output. Files: ${list}`
    )
  }
  return { byKey, unrecognized }
}
