// GENERATED by aurora-mcp/scripts/sync-separation.mjs from aurora/src/shared/separation/mvsep-catalog.generated.ts. Do not edit: edit the app's file
// and run `node scripts/sync-separation.mjs`. `--check` (in npm run typecheck) fails on drift.
// GENERATED by tools/gen-mvsep-catalog.ts from https://mvsep.com/api/app/algorithms on 2026-10-02. Do not edit by hand; rerun the tool.
// Key = sep_type (the record's render_id). `outputs`: every output key MVSEP declares or was seen returning,
// with its display label (the `type` field of a result file).

export interface MvsepField {
  serverKey: string
  label: string
  default: string | null
  options: Record<string, string>
}

export interface MvsepAlgorithm {
  name: string
  priceCoefficient: number
  outputs: Record<string, string>
  fields: Record<string, MvsepField>
}

export const MVSEP_CATALOG_DATE = '2026-10-02'

export const MVSEP_ALGORITHMS: Record<number, MvsepAlgorithm> = {
  "0": {
    "name": "spleeter",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "accompaniment": "Accompaniment"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "0",
        "options": {
          "0": "2 stems (vocals, music)",
          "1": "4 stems (vocals, drums, bass, other)",
          "2": "5 stems (vocals, drums, bass, piano, other)"
        }
      }
    }
  },
  "3": {
    "name": "UnMix",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "drums": "Drums",
      "bass": "Bass",
      "other": "Other",
      "instrumental": "Instrumental",
      "noise": "Noise",
      "speech": "Speech"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "0",
        "options": {
          "0": "unmix XL (vocals, drums, bass, other)",
          "1": "unmix HQ (vocals, drums, bass, other)",
          "2": "unmix SD (vocals, drums, bass, other)",
          "3": "unmix SE (vocals, music) - low quality"
        }
      }
    }
  },
  "7": {
    "name": "MDX A/B (vocals, drums, bass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "bass": "Bass",
      "drums": "Drums",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Vocal model type",
        "default": "3",
        "options": {
          "0": "MDX A (Contest Version)",
          "1": "MDX UVR 2022.01.01 SDR 8.62",
          "2": "MDX UVR 2022.07.25 SDR 8.51",
          "3": "MDX Kimberley Jensen 2023.02.12 SDR: 9.30 (New)"
        }
      }
    }
  },
  "9": {
    "name": "Ultimate Vocal Remover VR (vocals, music)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "instruments": "Instrumental",
      "other": "Other",
      "vocalsback": "Vocalsback",
      "drums": "Drums"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "0",
        "options": {
          "0": "HP2-4BAND-3090_4band_arch-500m_1",
          "1": "HP2-4BAND-3090_4band_2",
          "2": "HP2-4BAND-3090_4band_1",
          "3": "HP_4BAND_3090",
          "4": "Vocal_HP_4BAND_3090",
          "5": "Vocal_HP_4BAND_3090_AGG",
          "6": "HP2-MAIN-MSB2-3BAND-3090",
          "7": "HP-4BAND-V2",
          "8": "HP-KAROKEE-MSB2-3BAND-3090 (Karaokee model)",
          "9": "WIP-Piano-4band-129605kb (Piano model)",
          "10": "drums-4BAND-3090_4band (Drums model)",
          "11": "bass-4BAND-3090_4band (Bass model)",
          "12": "karokee_4band_v2_sn (Karaokee model v2)",
          "13": "UVR-De-Echo-Aggressive",
          "14": "UVR-De-Echo-Normal",
          "15": "UVR-DeNoise",
          "16": "UVR-DeEcho-DeReverb",
          "17": "UVR-BVE-4B_SN-44100-1 (Back vocals model)"
        }
      },
      "add_opt2": {
        "serverKey": "agg",
        "label": "Agressiveness",
        "default": "0.3",
        "options": {
          "0.3": "0.3",
          "0.1": "0.1",
          "0.2": "0.2",
          "0.4": "0.4",
          "0.5": "0.5",
          "0.6": "0.6",
          "0.7": "0.7",
          "0.8": "0.8",
          "0.9": "0.9",
          "1.0": "1.0"
        }
      }
    }
  },
  "10": {
    "name": "Demucs3 Model (vocals, drums, bass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "drums": "Drums",
      "bass": "Bass",
      "other": "Other",
      "instrumental": "Instrumental"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "1",
        "options": {
          "0": "Demucs3 Model A (Contest Version)",
          "1": "Demucs3 Model B (High Quality) "
        }
      }
    }
  },
  "12": {
    "name": "MDX-B Karaoke (lead/back vocals)",
    "priceCoefficient": 1,
    "outputs": {
      "vocalslead": "Lead vocals",
      "instrum": "Instrumental + back vocals",
      "instrumonly": "Instrumonly",
      "vocalsback": "Vocalsback",
      "vocalsfull": "Vocalsfull"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Karaoke model type",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture (SDR lead vocals: 6.81)",
          "1": "Extract from vocals part (SDR lead vocals: 7.94)"
        }
      }
    }
  },
  "13": {
    "name": "Demucs2 (vocals, drums, bass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "drums": "Drums",
      "bass": "Bass",
      "other": "Other",
      "instrumental": "Instrumental"
    },
    "fields": {}
  },
  "14": {
    "name": "Zero Shot (Query Based) (Low quality)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "invert": "Inverted residue",
      "other": "Other",
      "bass": "Bass",
      "drums": "Drums"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "vector",
        "label": "Model Type",
        "default": "2",
        "options": {
          "0": "Bass (MUSDB18HQ AVG)",
          "1": "Drums (MUSDB18HQ AVG)",
          "2": "Vocals (MUSDB18HQ AVG)",
          "3": "Other (MUSDB18HQ AVG)"
        }
      }
    }
  },
  "15": {
    "name": "Danna Sep (vocals, drums, bass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "drums": "Drums",
      "bass": "Bass",
      "other": "Other",
      "instrumental": "Instrumental"
    },
    "fields": {}
  },
  "16": {
    "name": "Byte Dance (vocals, drums, bass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "instrumental": "Instrumental"
    },
    "fields": {}
  },
  "17": {
    "name": "UVRv5 Demucs (vocals, music)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "instrumental": "Instrumental"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": null,
        "options": {
          "0": "UVR_Demucs_Model_1",
          "1": "UVR_Demucs_Model_2",
          "2": "UVR_Demucs_Model_Bag"
        }
      }
    }
  },
  "18": {
    "name": "MVSep DNR (music, sfx, speech)",
    "priceCoefficient": 1,
    "outputs": {
      "speech": "Speech",
      "music": "Music",
      "sfx": "SFX",
      "sum": "Sum (all stems)"
    },
    "fields": {}
  },
  "19": {
    "name": "MVSep Old Vocal Model (vocals, music)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "instrumental": "Instrumental"
    },
    "fields": {}
  },
  "20": {
    "name": "Demucs4 HT (vocals, drums, bass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "drums": "Drums",
      "bass": "Bass",
      "other": "Other",
      "instrumental": "Instrumental",
      "guitar": "Guitar",
      "piano": "Piano"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "1",
        "options": {
          "0": "htdemucs_ft (High Quality, Slow)",
          "1": "htdemucs (Good Quality, Fast)",
          "2": "htdemucs_6s (6 stems, additional piano and guitar)"
        }
      }
    }
  },
  "22": {
    "name": "Reverb Removal (noreverb)",
    "priceCoefficient": 1,
    "outputs": {
      "noreverb": "Noreverb",
      "reverb": "Reverb",
      "dry": "No reverb (dry)",
      "other": "Reverb",
      "instrum": "Instrum",
      "restored": "Restored",
      "vocals": "Vocals"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "7",
        "options": {
          "0": "Reverb removal by FoxJoy (MDX-B)",
          "1": "Reverb removal by anvuew (MelRoformer)",
          "2": "Reverb removal by anvuew (BSRoformer)",
          "3": "Reverb removal by anvuew v2 (MelRoformer)",
          "4": "Reverb removal by Sucial (MelRoformer)",
          "5": "Reverb removal by Sucial v2 (MelRoformer)",
          "6": "DeReverb room by anvuew (BSRoformer)",
          "7": "DeReverb stereo by anvuew (BSRoformer)",
          "8": "Reverb removal by aufr33 and jarredou (MDX23C)",
          "9": "MVSep Team (2026.07, BSRoformer)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "Preprocess",
        "default": "1",
        "options": {
          "0": "Extract vocals (needed for Mel/BS Roformer)",
          "1": "Use as is"
        }
      }
    }
  },
  "23": {
    "name": "MDX B (vocals, instrumental)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "instrum": "Instrumental"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Vocal model type",
        "default": "11",
        "options": {
          "0": "MDX UVR 2022.01.01 (SDR: 8.83)",
          "1": "MDX UVR 2022.07.25(SDR: 8.67)",
          "2": "MDX Kimberley Jensen v1 2023.02.12  (SDR: 9.48)",
          "4": "UVR-MDX-NET-Inst_HQ_2 (SDR: 9.12)",
          "5": "UVR_MDXNET_Main (SDR: 8.79)",
          "6": "MDX Kimberley Jensen Inst (SDR: 9.28)",
          "7": "MDX Kimberley Jensen v2 2023.05.21 (SDR: 9.60)",
          "8": "UVR-MDX-NET-Inst_HQ_3 (SDR: 9.38)",
          "9": "UVR-MDX-NET-Voc_FT (SDR: 9.64)",
          "11": "UVR-MDX-NET-Inst_HQ_4 (SDR: 9.71)",
          "12": "UVR-MDX-NET-Inst_HQ_5 (SDR: 9.45)"
        }
      }
    }
  },
  "24": {
    "name": "MVSep Demucs4HT DNR (speech, music, effects)",
    "priceCoefficient": 1,
    "outputs": {
      "dialog": "Dialog",
      "music": "Music",
      "effect": "Effects",
      "instrumental": "Instrumental (no dialog)"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "0",
        "options": {
          "0": "Single (SDR: 9.62)",
          "1": "Ensemble (SDR: 10.16)"
        }
      }
    }
  },
  "25": {
    "name": "MDX23C (vocals, instrumental)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Vocal model type",
        "default": "7",
        "options": {
          "0": "12K FFT (SDR vocals: 9.68, SDR instrum: 15.99)",
          "1": "12K FFT, 6 Poolings (SDR vocals: 9.49, SDR instrum: 15.79)",
          "2": "12K FFT, Large Conv (SDR vocals: 9.71, SDR instrum: 16.02)",
          "3": "12K FFT, Large Conv, Hop 1024 (SDR vocals: 9.95, SDR instrum: 16.26)",
          "4": "8K FFT (SDR vocals: 10.17, SDR instrum: 16.48)",
          "7": "8K FFT (SDR vocals: 10.36, SDR instrum: 16.66)"
        }
      }
    }
  },
  "26": {
    "name": "Ensemble (vocals, instrum)",
    "priceCoefficient": 2,
    "outputs": {
      "vocals": "Vocals",
      "other": "Other"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "7",
        "options": {
          "1": "SDR Vocals 10.44 (MDX23C, VitLarge23, Demucs4HT)",
          "2": "SDR Vocals 10.75 (MDX23C, BS Roformer (v1), VitLarge23)",
          "3": "SDR Vocals 11.06 (MDX23C, BS Roformer (viperx))",
          "4": "SDR Vocals 11.33 (MDX23C, BS Roformer (finetuned))",
          "5": "SDR Vocals 11.50 (Mel Roformer and BS Roformer)",
          "6": "SDR Vocals 11.61 (Mel Roformer, BS Roformer and SCNet XL)",
          "7": "SDR Vocals 11.93 (Mel Roformer, BS Roformer (x2) and SCNet XL IHF)",
          "8": "High Vocal Fullness (SDR: 11.69, Fullness: 20.46)",
          "9": "High Instrumental Fullness  (SDR: 17.69, Fullness: 34.79)"
        }
      },
      "add_opt1": {
        "serverKey": "detailed",
        "label": "Output files",
        "default": "0",
        "options": {
          "0": "Standard set",
          "1": "Include intermediate results and max_fft, min_fft"
        }
      }
    }
  },
  "27": {
    "name": "Demucs4 Vocals 2023 (vocals, instrum)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "instrumental": "Instrumental"
    },
    "fields": {}
  },
  "28": {
    "name": "Ensemble (vocals, instrum, bass, drums, other)",
    "priceCoefficient": 4,
    "outputs": {
      "vocals": "Vocals",
      "instrum": "Instrumental",
      "bass": "Bass",
      "drums": "Drums",
      "other": "Other",
      "piano": "Piano",
      "guitar": "Guitar",
      "bass-bsroformer-sw": "Bass bsroformer sw",
      "bass-scnet-xl": "Bass scnet xl",
      "drums-bsroformer-sw": "Drums bsroformer sw",
      "drums-melroformer": "Drums melroformer",
      "drums-scnet": "Drums scnet",
      "instrum-bs-roformer-v1": "Instrum bs roformer v1",
      "instrum-bs-roformer-v2": "Instrum bs roformer v2",
      "instrum-max-fft": "Instrum max fft",
      "instrum-mel-roformer": "Instrum mel roformer",
      "instrum-min-fft": "Instrum min fft",
      "instrum-scnet-xl-ihf": "Instrum scnet xl ihf",
      "vocals-bs-roformer-v1": "Vocals bs roformer v1",
      "vocals-bs-roformer-v2": "Vocals bs roformer v2",
      "vocals-bsroformer-sw": "Vocals bsroformer sw",
      "vocals-max-fft": "Vocals max fft",
      "vocals-mel-roformer": "Vocals mel roformer",
      "vocals-min-fft": "Vocals min fft",
      "vocals-scnet-xl-ihf": "Vocals scnet xl ihf"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "11",
        "options": {
          "1": "SDR average: 11.21 (v. 2023.09.01)",
          "2": "SDR average: 11.87 (v. 2024.03.08)",
          "3": "SDR average: 12.03 (v. 2024.03.28)",
          "4": "SDR average: 12.17 (v. 2024.04.04)",
          "5": "SDR average: 12.34 (v. 2024.05.21)",
          "6": "SDR average: 12.66 (v. 2024.07.14)",
          "7": "SDR average: 12.76 (v. 2024.08.15)",
          "8": "SDR average: 12.84 (v. 2024.10.08)",
          "9": "SDR average: 13.01 (v. 2024.12.20)",
          "10": "SDR average: 13.07 (v. 2024.12.28)",
          "11": "SDR average: 13.67 (v. 2025.06.30)"
        }
      },
      "add_opt1": {
        "serverKey": "detailed",
        "label": "Output files",
        "default": "0",
        "options": {
          "0": "Standard set",
          "1": "Include intermediate results and max_fft, min_fft"
        }
      }
    }
  },
  "29": {
    "name": "MVSep Piano (piano, other)",
    "priceCoefficient": 1,
    "outputs": {
      "piano": "Piano",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Piano model type",
        "default": "5",
        "options": {
          "0": "mdx23c (2023.08, SDR: 4.79)",
          "1": "mdx23c (2024.09, SDR: 5.59)",
          "2": "MelRoformer (viperx, SDR: 5.71)",
          "3": "SCNet Large (2024.09, SDR: 5.89)",
          "4": "Ensemble (SCNet + Mel, SDR: 6.20)",
          "5": "BS Roformer SW (SDR: 7.83)"
        }
      }
    }
  },
  "30": {
    "name": "Ensemble All-In (vocals, bass, drums, piano, guitar, lead/back vocals, other)",
    "priceCoefficient": 6,
    "outputs": {
      "vocals": "Vocals",
      "instrum": "Instrumental",
      "bass": "Bass",
      "drums": "Drums",
      "guitar": "Guitar",
      "piano": "Piano",
      "strings": "Strings",
      "wind": "Wind",
      "other-no-vocals-bass-drums": "Other (no vocals/bass/drums)",
      "vocals-lead-v1": "Lead vocals (v1)",
      "vocals-lead-v2": "Lead vocals (v2)",
      "vocals-back": "Back vocals",
      "back-instrum": "Back vocals + instrumental",
      "drums-kick": "Drums: kick",
      "drums-snare": "Drums: snare",
      "drums-cymbals": "Drums: cymbals",
      "drums-toms": "Drums: toms",
      "drums-hh": "Drums: hi-hat",
      "drums-ride": "Drums: ride",
      "drums-crash": "Drums: crash"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "11",
        "options": {
          "1": "SDR average: 11.21 (v. 2023.09.01)",
          "2": "SDR average: 11.87 (v. 2024.03.08)",
          "3": "SDR average: 12.03 (v. 2024.03.28)",
          "4": "SDR average: 12.17 (v. 2024.04.04)",
          "5": "SDR average: 12.32 (v. 2024.05.21)",
          "6": "SDR average: 12.66 (v. 2024.07.14)",
          "7": "SDR average: 12.76 (v. 2024.08.15)",
          "8": "SDR average: 12.84 (v. 2024.10.08)",
          "9": "SDR average: 13.01 (v. 2024.12.20)",
          "10": "SDR average: 13.07 (v. 2024.12.28)",
          "11": "SDR average: 13.67 (v. 2025.06.30)"
        }
      },
      "add_opt1": {
        "serverKey": "detailed",
        "label": "Output files",
        "default": "0",
        "options": {
          "0": "Standard set",
          "1": "Include intermediate results and max_fft, min_fft"
        }
      }
    }
  },
  "31": {
    "name": "MVSep Guitar (guitar, other)",
    "priceCoefficient": 1,
    "outputs": {
      "guitar": "Guitar",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Guitar model type",
        "default": "7",
        "options": {
          "0": "mdx23c (2023.08, SDR: 4.78)",
          "2": "mdx23c (2024.06, SDR: 6.34)",
          "3": "MelRoformer (2024.06, SDR: 7.02)",
          "5": "BSRoformer (viperx, SDR: 7.16)",
          "6": "Ensemble (BS + Mel, SDR: 7.51)",
          "7": "BS Roformer SW (SDR: 9.05)"
        }
      }
    }
  },
  "33": {
    "name": "Vit Large 23 (vocals, instrum)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "1",
        "options": {
          "0": "v1 (SDR vocals: 9.78)",
          "1": "v2 (SDR vocals: 9.90)"
        }
      }
    }
  },
  "34": {
    "name": "MVSep Crowd removal (crowd, other)",
    "priceCoefficient": 1,
    "outputs": {
      "crowd": "Crowd",
      "other": "Other",
      "crowd-mdx23c": "Crowd mdx23c",
      "crowd-melroformer": "Crowd melroformer"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "2",
        "options": {
          "0": "Mel Roformer (SDR crowd: 6.07)",
          "1": "Ensemble MDX23C + Mel Roformer (SDR crowd: 6.27)",
          "2": "BS Roformer (SDR crowd: 7.21)",
          "8": "MDX23C v1 (SDR crowd: 5.57)",
          "9": "MDX23C v2 (SDR crowd: 6.06)"
        }
      }
    }
  },
  "36": {
    "name": "BandIt Plus (speech, music, effects)",
    "priceCoefficient": 1,
    "outputs": {
      "speech": "Speech",
      "music": "Music",
      "effects": "Effects"
    },
    "fields": {}
  },
  "37": {
    "name": "DrumSep (4-6 stems: kick, snare, cymbals, toms, ride, hh, crash)",
    "priceCoefficient": 1,
    "outputs": {
      "drums": "Drums (full)",
      "kick": "Kick",
      "snare": "Snare",
      "toms": "Toms",
      "ride": "Ride",
      "hh": "Hi-hat",
      "crash": "Crash",
      "residual": "Residual",
      "cymbals": "Cymbals",
      "crash-ride": "Crash ride"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "7",
        "options": {
          "0": "DrumSep model by inagoy (HDemucs, 4 stems)",
          "1": "DrumSep model by aufr33 and jarredou (MDX23C, 6 stems)",
          "2": "DrumSep SCNet XL (5 stems)",
          "3": "DrumSep SCNet XL (6 stems)",
          "4": "DrumSep SCNet XL (4 stems)",
          "5": "DrumSep Ensemble of 4 models (MDX23C + 3 * SCNet XL, 8 stems)",
          "6": "DrumSep MelBand Roformer (4 stems)",
          "7": "DrumSep MelBand Roformer (6 stems)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "Preprocess",
        "default": "0",
        "options": {
          "0": "Apply Drums model before",
          "1": "Use as is (audio must contain drums only)"
        }
      }
    }
  },
  "38": {
    "name": "LarsNet (kick, snare, cymbals, toms, hihat)",
    "priceCoefficient": 1,
    "outputs": {
      "drums": "Drums (full)",
      "other": "Other (no drums)",
      "kick": "Kick",
      "snare": "Snare",
      "toms": "Toms",
      "hihat": "Hi-hat",
      "cymbals": "Cymbals"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "0",
        "options": {
          "0": "Apply Demucs4HT first to get drums",
          "1": "Use as is (audio must contain drums only)"
        }
      }
    }
  },
  "40": {
    "name": "BS Roformer (vocals, instrumental)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "other": "Other",
      "instrum": "Instrumental",
      "vocals-fullness-level-1": "Vocals (fullness 1)",
      "instrum-fullness-level-1": "Instrumental (fullness 1)",
      "vocals-fullness-level-2": "Vocals (fullness 2)",
      "vocals-fullness-level-3": "Vocals (fullness 3)"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Vocal model type",
        "default": "81",
        "options": {
          "3": "ver. 2024.02 (SDR vocals: 10.42, SDR instrum: 16.73)",
          "4": "viperx edition (SDR vocals: 10.87, SDR instrum: 17.17)",
          "5": "ver 2024.04 (SDR vocals: 11.24, SDR instrum: 17.55)",
          "29": "ver 2024.08 (SDR vocals: 11.31, SDR instrum: 17.62)",
          "81": "ver 2025.07 (SDR vocals: 11.89, SDR instrum: 18.20)",
          "85": "unwa high instrum fullness (SDR instrum: 17.25)",
          "142": "unwa BS Roformer HyperACE v2 instrum (SDR instrum: 17.40)",
          "143": "unwa  BS Roformer HyperACE v2 vocals (SDR vocals: 11.39)",
          "171": "124 bands (SDR vocals: 12.33, SDR instrum: 18.64)",
          "172": "becruily high instrum fullness 124 bands (SDR instrum: 18.47)"
        }
      },
      "add_opt2": {
        "serverKey": "overlap",
        "label": "Overlap",
        "default": "2",
        "options": {
          "2": "50%",
          "8": "87.5%"
        }
      },
      "add_opt3": {
        "serverKey": "extract_type",
        "label": "Set of stems",
        "default": "0",
        "options": {
          "0": "Standard",
          "1": "Include fullness stems"
        }
      }
    }
  },
  "41": {
    "name": "MVSep Bass (bass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "bass": "Bass",
      "other": "Other",
      "vocals": "Vocals",
      "bass-bsroformer-sw": "Bass bsroformer sw",
      "bass-scnet-xl": "Bass scnet xl"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Bass model type",
        "default": "5",
        "options": {
          "0": "BS Roformer (SDR bass: 12.49)",
          "1": "HTDemucs4 (SDR bass: 12.52)",
          "2": "SCNet XL (SDR bass: 13.81)",
          "3": "BS + HTDemucs + SCNet (SDR bass: 14.07)",
          "4": "BS Roformer SW (SDR bass: 14.62)",
          "5": "BS Roformer SW + SCNet XL (SDR bass: 14.87)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from instrumental part"
        }
      },
      "add_opt3": {
        "serverKey": "detailed",
        "label": "Output files",
        "default": "0",
        "options": {
          "0": "Standard set",
          "1": "Include results of independent models"
        }
      }
    }
  },
  "42": {
    "name": "MVSep MultiSpeaker (MDX23C)",
    "priceCoefficient": 1,
    "outputs": {
      "vocal1": "Voice 1",
      "vocal2": "Voice 2"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "1",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from vocals part"
        }
      }
    }
  },
  "43": {
    "name": "MVSep Multichannel BS (vocals, instrumental)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "0",
        "options": {
          "0": "BS Roformer (SDR: 11.89)",
          "1": "MDX23C (SDR: 10.36)",
          "2": "MelBand Roformer (SDR: 11.17)",
          "3": "MelBand Roformer XL (SDR: 11.28)",
          "4": "BS Roformer 124 bands (SDR: 12.33)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "Processing Mode",
        "default": "1",
        "options": {
          "0": "Per-Channel",
          "1": "Stereo Pairs"
        }
      }
    }
  },
  "44": {
    "name": "MVSep Drums (drums, other)",
    "priceCoefficient": 1,
    "outputs": {
      "drums": "Drums",
      "other": "Other",
      "vocals": "Vocals",
      "drums-bsroformer-sw": "Drums bsroformer sw",
      "drums-melroformer": "Drums melroformer",
      "drums-scnet": "Drums scnet"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Drums model type",
        "default": "6",
        "options": {
          "0": "HTDemucs (SDR drums: 12.04)",
          "1": "MelBand Roformer (SDR drums: 12.76)",
          "2": "SCNet Large (SDR drums: 13.01)",
          "3": "SCNet XL (SDR drums: 13.42)",
          "4": "Mel + SCNet XL (SDR drums: 13.78)",
          "5": "BS Roformer SW (SDR drums: 14.11)",
          "6": "Mel + SCNet XL + BS Roformer SW (SDR drums: 14.35)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from instrumental part"
        }
      },
      "add_opt3": {
        "serverKey": "detailed",
        "label": "Output files",
        "default": "0",
        "options": {
          "0": "Standard set",
          "1": "Include results of independent models"
        }
      }
    }
  },
  "45": {
    "name": "BandIt v2 (speech, music, effects)",
    "priceCoefficient": 1,
    "outputs": {
      "speech": "Speech",
      "music": "Music",
      "sfx": "SFX"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model Type",
        "default": "0",
        "options": {
          "0": "Multi language model",
          "1": "English model",
          "2": "German model",
          "3": "French model",
          "4": "Spanish model",
          "5": "Chinese model",
          "6": "Faroese model"
        }
      }
    }
  },
  "46": {
    "name": "SCNet (vocals, instrumental)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Vocal model type",
        "default": "5",
        "options": {
          "0": "SCNet (SDR vocals: 10.25, SDR instrum: 16.56)",
          "1": "SCNet Large (SDR vocals: 10.74, SDR instrum: 17.05)",
          "2": "SCNet XL (SDR vocals: 10.96, SDR instrum: 17.27)",
          "3": "SCNet XL (high fullness)",
          "4": "SCNet XL (very high fullness)",
          "5": "SCNet XL IHF (SDR vocals: 11.11, SDR instrum: 17.41)",
          "6": "SCNet XL IHF (high instrum fullness by becruily)"
        }
      }
    }
  },
  "47": {
    "name": "DeNoise by aufr33 and gabox",
    "priceCoefficient": 1,
    "outputs": {
      "dry": "Clean (dry)",
      "other": "Noise"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "0",
        "options": {
          "0": "aufr33 (Standard)",
          "1": "aufr33 (Aggressive)",
          "2": "gabox"
        }
      }
    }
  },
  "48": {
    "name": "MelBand Roformer (vocals, instrumental)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Vocal model type",
        "default": "4",
        "options": {
          "0": "Kimberley Jensen edition (SDR vocals: 11.01, SDR instrum: 17.32)",
          "1": "ver 2024.08 (SDR vocals: 11.17, SDR instrum: 17.48)",
          "2": "Bas Curtiz edition (SDR vocals: 11.18, SDR instrum: 17.49)",
          "3": "unwa Instrumental v1 (SDR vocals: 10.24, SDR instrum: 16.54)",
          "4": "ver 2024.10 (SDR vocals: 11.28, SDR instrum: 17.59)",
          "5": "unwa Instrumental v1e (SDR vocals: 10.05, SDR instrum: 16.36)",
          "6": "unwa big beta v5e (SDR vocals: 10.59, SDR instrum: 16.89)",
          "7": "becruily instrum high fullness (SDR instrum: 16.47)",
          "8": "becruily vocals high fullness (SDR vocals: 10.55)",
          "9": "unwa Instrumental v1e plus (SDR vocals: 10.33, SDR instrum: 16.64)",
          "10": "gabox Instrumental v7 (SDR vocals: 10.32, SDR instrum: 16.63)",
          "11": "becruily deux (SDR vocals: 11.35, SDR instrum: 17.66)",
          "12": "gabox v10 flowers (SDR vocals: 10.67, SDR instrum: 16.97)"
        }
      },
      "add_opt2": {
        "serverKey": "overlap",
        "label": "Overlap",
        "default": "2",
        "options": {
          "2": "50%",
          "8": "87.5%"
        }
      }
    }
  },
  "49": {
    "name": "MVSep Karaoke (lead/back vocals)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals-lead": "Lead vocals",
      "vocals-back": "Back vocals",
      "instrum-only": "Instrumental only",
      "back-instrum": "Back vocals + instrumental",
      "vocals-full": "Vocals full"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Karaoke model type",
        "default": "6",
        "options": {
          "0": "Model by viperx and aufr33 (SDR: 9.45)",
          "1": "Model by becruily (SDR: 9.61)",
          "2": "Model by gabox (SDR: 9.67)",
          "3": "Model fuzed gabox & aufr33/viperx (SDR: 9.85)",
          "4": "SCNet XL IHF by becruily (SDR: 9.53)",
          "5": "BS Roformer by frazer and becruily (SDR: 10.11)",
          "6": "BS Roformer by MVSep Team (SDR: 10.41)",
          "7": "BS Roformer by anvuew (SDR: 10.22)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "Extraction type",
        "default": "0",
        "options": {
          "0": "Use as is",
          "1": "Extract vocals first"
        }
      }
    }
  },
  "50": {
    "name": "Aspiration (by Sucial)",
    "priceCoefficient": 1,
    "outputs": {
      "aspiration": "Aspiration",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from vocals part"
        }
      }
    }
  },
  "52": {
    "name": "MVSep Bowed Strings (strings, other)",
    "priceCoefficient": 1,
    "outputs": {
      "strings": "Strings",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "String model type",
        "default": "1",
        "options": {
          "0": "MDX23C (SDR strings: 3.84)",
          "1": "BS Roformer (SDR strings: 5.41)",
          "2": "BS Roformer by gilliaan (SDR strings: 4.69)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from instrumental part"
        }
      }
    }
  },
  "53": {
    "name": "Medley Vox (Multi-singer separation)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals1": "Voice 1",
      "vocals2": "Voice 2"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "1",
        "options": {
          "0": "Apply to original file",
          "1": "Extract vocals first"
        }
      }
    }
  },
  "54": {
    "name": "MVSep Wind (wind, other)",
    "priceCoefficient": 1,
    "outputs": {
      "wind": "Wind",
      "other": "Other",
      "vocals": "Vocals"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Wind model type",
        "default": "3",
        "options": {
          "0": "MelBand Roformer (SDR wind: 6.73)",
          "1": "SCNet Large (SDR wind: 6.76)",
          "2": "Mel + SCNet (SDR wind: 7.22)",
          "3": "BS Roformer (SDR wind: 9.82)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from instrumental part"
        }
      },
      "add_opt3": {
        "serverKey": "detailed",
        "label": "Output files",
        "default": "0",
        "options": {
          "0": "Standard set",
          "1": "Include results of independent models"
        }
      }
    }
  },
  "55": {
    "name": "Phantom Centre extraction",
    "priceCoefficient": 1,
    "outputs": {
      "center": "Center",
      "wide": "Wide (sides)",
      "difference": "Difference",
      "similarity": "Similarity"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "1",
        "options": {
          "0": "Phantom Centre by wesleyr36 (MDX23C)",
          "1": "Phantom Centre by gilliaan (BSRoformer)",
          "2": "Phantom Centre by gilliaan (mdx23c)"
        }
      }
    }
  },
  "56": {
    "name": "MVSep DnR v3 (speech, music, effects)",
    "priceCoefficient": 1,
    "outputs": {
      "speech": "Speech",
      "music": "Music",
      "sfx": "SFX"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "2",
        "options": {
          "0": "SCNet Large (SDR avg: 11.22)",
          "1": "MelBand Roformer (SDR avg: 10.99)",
          "2": "Mel + SCNet (SDR avg: 11.54)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Use vocals model to help"
        }
      },
      "add_opt3": {
        "serverKey": "detailed",
        "label": "Output files",
        "default": "0",
        "options": {
          "0": "Standard set",
          "1": "Include results of independent models"
        }
      }
    }
  },
  "57": {
    "name": "MVSep Male/Female separation",
    "priceCoefficient": 1,
    "outputs": {
      "male": "Male vocals",
      "female": "Female vocals",
      "instrumental": "Instrumental",
      "instrumental-plus-female": "Instrumental plus female",
      "instrumental-plus-male": "Instrumental plus male",
      "vocals": "Vocals"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "2",
        "options": {
          "0": "BSRoformer by Sucial (SDR: 6.52)",
          "1": "SCNet XL (SDR: 11.83)",
          "2": "MelRoformer (2025.01) (SDR: 13.03)",
          "3": "BSRoformer by aufr33 (SDR: 8.18)"
        }
      },
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract vocals first with BS Roformer"
        }
      }
    }
  },
  "58": {
    "name": "MVSep Organ (organ, other)",
    "priceCoefficient": 1,
    "outputs": {
      "organ": "Organ",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Organ model type",
        "default": "3",
        "options": {
          "0": "SCNet XL (SDR organ: 2.71)",
          "1": "MelBand Roformer (SDR organ: 2.77)",
          "2": "Mel + SCNet (SDR organ: 3.05)",
          "3": "BS Roformer (SDR organ: 5.08)"
        }
      }
    }
  },
  "61": {
    "name": "MVSep Saxophone (saxophone, other)",
    "priceCoefficient": 1,
    "outputs": {
      "saxophone": "Saxophone",
      "other": "Other",
      "saxophone-melroformer": "Saxophone melroformer",
      "saxophone-scnet": "Saxophone scnet"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "3",
        "options": {
          "0": "SCNet XL (SDR saxophone: 6.15)",
          "1": "MelBand Roformer (SDR saxophone: 6.97)",
          "2": "Mel + SCNet (SDR saxophone: 7.13)",
          "3": "BS Roformer (SDR saxophone: 9.77)"
        }
      }
    }
  },
  "63": {
    "name": "BS Roformer SW (vocals, bass, drums, guitar, piano, other)",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "bass": "Bass",
      "drums": "Drums",
      "guitar": "Guitar",
      "piano": "Piano",
      "other": "Other",
      "instrum": "Instrumental"
    },
    "fields": {}
  },
  "65": {
    "name": "MVSep Violin (violin, other)",
    "priceCoefficient": 1,
    "outputs": {
      "violin": "Violin",
      "other": "Other"
    },
    "fields": {}
  },
  "66": {
    "name": "MVSep Acoustic Guitar (acoustic-guitar, other)",
    "priceCoefficient": 1,
    "outputs": {
      "acoustic-guitar": "Acoustic guitar",
      "other": "Other",
      "all-guitar": "All guitar",
      "no-guitar": "No guitar",
      "other-guitar": "Other guitar"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from guitar part"
        }
      }
    }
  },
  "67": {
    "name": "MVSep Flute (flute, other)",
    "priceCoefficient": 1,
    "outputs": {
      "flute": "Flute",
      "other": "Other",
      "all-wind": "All wind",
      "no-wind": "No wind",
      "other-wind": "Other wind"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      },
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Flute model type",
        "default": "1",
        "options": {
          "0": "SCNet XL (SDR flute: 6.27)",
          "1": "BS Roformer (SDR flute: 9.46)"
        }
      }
    }
  },
  "69": {
    "name": "MVSep Viola (viola, other)",
    "priceCoefficient": 1,
    "outputs": {
      "viola": "Viola",
      "other": "Other",
      "all-strings": "All strings",
      "no-strings": "No strings",
      "other-strings": "Other strings"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from strings part"
        }
      }
    }
  },
  "70": {
    "name": "MVSep Cello (cello, other)",
    "priceCoefficient": 1,
    "outputs": {
      "cello": "Cello",
      "other": "Other",
      "all-strings": "All strings",
      "no-strings": "No strings",
      "other-strings": "Other strings"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from strings part"
        }
      }
    }
  },
  "71": {
    "name": "MVSep Trumpet (trumpet, other)",
    "priceCoefficient": 1,
    "outputs": {
      "trumpet": "Trumpet",
      "other": "Other",
      "all-wind": "All wind",
      "no-wind": "No wind",
      "other-wind": "Other wind"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "72": {
    "name": "MVSep Harp (harp, other)",
    "priceCoefficient": 1,
    "outputs": {
      "harp": "Harp",
      "other": "Other"
    },
    "fields": {}
  },
  "73": {
    "name": "MVSep Double Bass (double-bass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "double-bass": "Double bass",
      "other": "Other",
      "all-strings": "All strings",
      "no-strings": "No strings",
      "other-strings": "Other strings"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from strings part"
        }
      }
    }
  },
  "74": {
    "name": "MVSep Mandolin (mandolin, other)",
    "priceCoefficient": 1,
    "outputs": {
      "mandolin": "Mandolin",
      "other": "Other"
    },
    "fields": {}
  },
  "75": {
    "name": "MVSep Trombone (trombone, other)",
    "priceCoefficient": 1,
    "outputs": {
      "trombone": "Trombone",
      "other": "Other",
      "all-wind": "All wind",
      "no-wind": "No wind",
      "other-wind": "Other wind"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "76": {
    "name": "MVSep Tambourine (tambourine, other)",
    "priceCoefficient": 1,
    "outputs": {
      "tambourine": "Tambourine",
      "other": "Other"
    },
    "fields": {}
  },
  "77": {
    "name": "MVSep Oboe (oboe, other)",
    "priceCoefficient": 1,
    "outputs": {
      "oboe": "Oboe",
      "other": "Other",
      "all-wind": "All wind",
      "no-wind": "No wind",
      "other-wind": "Other wind"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "78": {
    "name": "MVSep Clarinet (clarinet, other)",
    "priceCoefficient": 1,
    "outputs": {
      "clarinet": "Clarinet",
      "other": "Other",
      "all-wind": "All wind",
      "no-wind": "No wind",
      "other-wind": "Other wind"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "79": {
    "name": "MVSep Digital Piano (digital-piano, other)",
    "priceCoefficient": 1,
    "outputs": {
      "digital-piano": "Digital piano",
      "other": "Other",
      "all-piano": "All piano",
      "no-piano": "No piano",
      "other-piano": "Other piano"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from piano part"
        }
      }
    }
  },
  "81": {
    "name": "MVSep Electric Guitar (electric-guitar, other)",
    "priceCoefficient": 1,
    "outputs": {
      "electric-guitar": "Electric guitar",
      "other": "Other",
      "all-guitar": "All guitar",
      "no-guitar": "No guitar",
      "other-guitar": "Other guitar"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from guitar part"
        }
      }
    }
  },
  "82": {
    "name": "MVSep French Horn (french-horn, other)",
    "priceCoefficient": 1,
    "outputs": {
      "french-horn": "French horn",
      "other": "Other",
      "all-wind": "All wind",
      "no-wind": "No wind",
      "other-wind": "Other wind"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "83": {
    "name": "MVSep Banjo (banjo, other)",
    "priceCoefficient": 1,
    "outputs": {
      "banjo": "Banjo",
      "other": "Other"
    },
    "fields": {}
  },
  "84": {
    "name": "MVSep Marimba (marimba, other)",
    "priceCoefficient": 1,
    "outputs": {
      "marimba": "Marimba",
      "other": "Other"
    },
    "fields": {}
  },
  "85": {
    "name": "MVSep Glockenspiel (glockenspiel, other)",
    "priceCoefficient": 1,
    "outputs": {
      "glockenspiel": "Glockenspiel",
      "other": "Other"
    },
    "fields": {}
  },
  "86": {
    "name": "MVSep Timpani (timpani, other)",
    "priceCoefficient": 1,
    "outputs": {
      "timpani": "Timpani",
      "other": "Other"
    },
    "fields": {}
  },
  "87": {
    "name": "MVSep Harmonica (harmonica, other)",
    "priceCoefficient": 1,
    "outputs": {
      "harmonica": "Harmonica",
      "other": "Other"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "88": {
    "name": "MVSep Synth (synth, other)",
    "priceCoefficient": 1,
    "outputs": {
      "synth": "Synth",
      "other": "Other",
      "instrum": "Instrum",
      "vocals": "Vocals"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from instrumental part"
        }
      }
    }
  },
  "89": {
    "name": "MVSep Triangle (triangle, other)",
    "priceCoefficient": 1,
    "outputs": {
      "triangle": "Triangle",
      "other": "Other"
    },
    "fields": {}
  },
  "90": {
    "name": "MVSep Sitar (sitar, other)",
    "priceCoefficient": 1,
    "outputs": {
      "sitar": "Sitar",
      "other": "Other"
    },
    "fields": {}
  },
  "91": {
    "name": "MVSep Harpsichord (harpsichord, other)",
    "priceCoefficient": 1,
    "outputs": {
      "harpsichord": "Harpsichord",
      "other": "Other"
    },
    "fields": {}
  },
  "92": {
    "name": "MVSep Tuba (tuba, other)",
    "priceCoefficient": 1,
    "outputs": {
      "tuba": "Tuba",
      "other": "Other"
    },
    "fields": {}
  },
  "93": {
    "name": "MVSep Bassoon (bassoon, other)",
    "priceCoefficient": 1,
    "outputs": {
      "bassoon": "Bassoon",
      "other": "Other"
    },
    "fields": {}
  },
  "94": {
    "name": "MVSep Congas (congas , other)",
    "priceCoefficient": 1,
    "outputs": {
      "congas": "Congas",
      "other": "Other"
    },
    "fields": {}
  },
  "95": {
    "name": "MVSep Bells (bells, other)",
    "priceCoefficient": 1,
    "outputs": {
      "bells": "Bells",
      "other": "Other"
    },
    "fields": {}
  },
  "96": {
    "name": "MVSep Ukulele (ukulele, other)",
    "priceCoefficient": 1,
    "outputs": {
      "ukulele": "Ukulele",
      "other": "Other"
    },
    "fields": {}
  },
  "97": {
    "name": "MVSep Dobro (dobro, other)",
    "priceCoefficient": 1,
    "outputs": {
      "dobro": "Dobro",
      "other": "Other"
    },
    "fields": {}
  },
  "98": {
    "name": "MVSep Wind Chimes (wind-chimes, other)",
    "priceCoefficient": 1,
    "outputs": {
      "wind-chimes": "Wind chimes",
      "other": "Other"
    },
    "fields": {}
  },
  "99": {
    "name": "MVSep Accordion (accordion, other)",
    "priceCoefficient": 1,
    "outputs": {
      "accordion": "Accordion",
      "other": "Other"
    },
    "fields": {}
  },
  "101": {
    "name": "MVSep Lead/Rhythm Guitar (lead-guitar, rhythm-guitar)",
    "priceCoefficient": 1,
    "outputs": {
      "lead-guitar": "Lead guitar",
      "rhythm-guitar": "Rhythm guitar",
      "all-guitar": "All guitar",
      "no-guitar": "No guitar"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "0",
        "options": {
          "0": "Two-stage model (SDR: 9.21)",
          "1": "One-stage model (SDR: 9.02)"
        }
      }
    }
  },
  "102": {
    "name": "MVSep Plucked Strings (plucked-strings, other)",
    "priceCoefficient": 1,
    "outputs": {
      "plucked-strings": "Plucked strings",
      "other": "Other"
    },
    "fields": {}
  },
  "105": {
    "name": "MVSep Percussion (percussion, other)",
    "priceCoefficient": 1,
    "outputs": {
      "percussion": "Percussion",
      "other": "Other"
    },
    "fields": {}
  },
  "106": {
    "name": "MVSep Keys (keys, other)",
    "priceCoefficient": 1,
    "outputs": {
      "keys": "Keys",
      "other": "Other"
    },
    "fields": {}
  },
  "107": {
    "name": "MVSep Brass (brass, other)",
    "priceCoefficient": 1,
    "outputs": {
      "brass": "Brass",
      "other": "Other",
      "all-wind": "All wind",
      "no-wind": "No wind",
      "other-wind": "Other wind"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "108": {
    "name": "MVSep Woodwind (woodwind, other)",
    "priceCoefficient": 1,
    "outputs": {
      "woodwind": "Woodwind",
      "other": "Other",
      "all-wind": "All wind",
      "no-wind": "No wind",
      "other-wind": "Other wind"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "109": {
    "name": "MVSep Xylophone (xylophone, other)",
    "priceCoefficient": 1,
    "outputs": {
      "xylophone": "Xylophone",
      "other": "Other"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from percussion part"
        }
      }
    }
  },
  "110": {
    "name": "MVSep Celesta (celesta, other)",
    "priceCoefficient": 1,
    "outputs": {
      "celesta": "Celesta",
      "other": "Other"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from percussion part"
        }
      }
    }
  },
  "111": {
    "name": "MVSep SATB Choir (soprano, alto, tenor, bass)",
    "priceCoefficient": 1,
    "outputs": {
      "soprano": "Soprano",
      "alto": "Alto",
      "tenor": "Tenor",
      "bass": "Bass",
      "instrum": "Instrum",
      "vocals": "Vocals"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract vocals first"
        }
      },
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "3",
        "options": {
          "2": "SCNet Masked (SDR: 4.07)",
          "3": "BS Roformer (SDR: 7.39)"
        }
      }
    }
  },
  "112": {
    "name": "MVSep Choir (choir, other)",
    "priceCoefficient": 1,
    "outputs": {
      "choir": "Choir",
      "other": "Other",
      "instrum": "Instrum",
      "other-vocals": "Other vocals",
      "vocals": "Vocals"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract vocals first"
        }
      }
    }
  },
  "116": {
    "name": "MVSep Bagpipes (bagpipes , other)",
    "priceCoefficient": 1,
    "outputs": {
      "bagpipes": "Bagpipes",
      "other": "Other"
    },
    "fields": {
      "add_opt2": {
        "serverKey": "extract_type",
        "label": "How to extract",
        "default": "0",
        "options": {
          "0": "Extract directly from mixture",
          "1": "Extract from wind part"
        }
      }
    }
  },
  "117": {
    "name": "MVSep Braam",
    "priceCoefficient": 1,
    "outputs": {
      "braam": "Braam",
      "other": "Other"
    },
    "fields": {}
  },
  "122": {
    "name": "MVSep FX",
    "priceCoefficient": 1,
    "outputs": {
      "fx": "FX",
      "other": "Other"
    },
    "fields": {}
  },
  "123": {
    "name": "BS PolarFormer (vocals, instrumental)",
    "priceCoefficient": 1,
    "outputs": {
      "instrumental": "Instrumental",
      "instrumental-fullness-level-1": "Instrumental fullness level 1",
      "vocals": "Vocals",
      "vocals-fullness-level-1": "Vocals fullness level 1",
      "other": "Other"
    },
    "fields": {
      "add_opt1": {
        "serverKey": "model_type",
        "label": "Model type",
        "default": "163",
        "options": {
          "158": "BS PolarFormer (62 bands, SDR: 11.75)",
          "163": "BS PolarFormer (124 bands, SDR: 12.02)"
        }
      },
      "add_opt2": {
        "serverKey": "overlap",
        "label": "Overlap",
        "default": "2",
        "options": {
          "2": "50%",
          "8": "87.5%"
        }
      }
    }
  },
  "124": {
    "name": "MVSep Pedal Steel Guitar",
    "priceCoefficient": 1,
    "outputs": {
      "pedal-steel-guitar": "Pedal steel guitar",
      "other": "Other"
    },
    "fields": {}
  },
  "125": {
    "name": "MVSep Risers",
    "priceCoefficient": 1,
    "outputs": {
      "risers": "Risers",
      "other": "Other"
    },
    "fields": {}
  },
  "126": {
    "name": "Mega 53-stem Model",
    "priceCoefficient": 1,
    "outputs": {
      "vocals": "Vocals",
      "lead-vocal": "Lead vocal",
      "back-vocal": "Back vocal",
      "drums": "Drums",
      "kick": "Kick",
      "snare": "Snare",
      "toms": "Toms",
      "hh": "Hi-hat",
      "percussion": "Percussion",
      "tambourine": "Tambourine",
      "timpani": "Timpani",
      "congas": "Congas",
      "triangle": "Triangle",
      "bells": "Bells",
      "glockenspiel": "Glockenspiel",
      "marimba": "Marimba",
      "bass": "Bass",
      "double-bass": "Double bass",
      "guitar": "Guitar",
      "acoustic-guitar": "Acoustic guitar",
      "electric-guitar": "Electric guitar",
      "banjo": "Banjo",
      "mandolin": "Mandolin",
      "ukulele": "Ukulele",
      "dobro": "Dobro",
      "sitar": "Sitar",
      "piano": "Piano",
      "digital-piano": "Digital piano",
      "harpsichord": "Harpsichord",
      "keys": "Keys",
      "organ": "Organ",
      "accordion": "Accordion",
      "synth": "Synth",
      "strings": "Strings",
      "violin": "Violin",
      "viola": "Viola",
      "cello": "Cello",
      "harp": "Harp",
      "brass": "Brass",
      "trumpet": "Trumpet",
      "trombone": "Trombone",
      "french-horn": "French horn",
      "tuba": "Tuba",
      "woodwind": "Woodwind",
      "flute": "Flute",
      "clarinet": "Clarinet",
      "oboe": "Oboe",
      "bassoon": "Bassoon",
      "saxophone": "Saxophone",
      "harmonica": "Harmonica",
      "wind": "Wind",
      "wind-chimes": "Wind chimes",
      "bowed_strings": "Strings"
    },
    "fields": {}
  },
  "128": {
    "name": "MVSep Cowbell",
    "priceCoefficient": 1,
    "outputs": {
      "cowbell": "Cowbell",
      "other": "Other"
    },
    "fields": {}
  },
  "129": {
    "name": "MVSep Vibraphone",
    "priceCoefficient": 1,
    "outputs": {
      "vibes": "Vibraphone",
      "other": "Other"
    },
    "fields": {}
  },
  "130": {
    "name": "MVSep Metal Bars",
    "priceCoefficient": 1,
    "outputs": {
      "metal-bars": "Metal bars",
      "other": "Other"
    },
    "fields": {}
  },
  "131": {
    "name": "MVSep Rhodes",
    "priceCoefficient": 1,
    "outputs": {
      "rhodes": "Rhodes",
      "other": "Other"
    },
    "fields": {}
  },
  "132": {
    "name": "MVSep Whistle",
    "priceCoefficient": 1,
    "outputs": {
      "whistle": "Whistle",
      "other": "Other"
    },
    "fields": {}
  },
  "133": {
    "name": "MVSep Clap",
    "priceCoefficient": 1,
    "outputs": {
      "clap": "Clap",
      "other": "Other"
    },
    "fields": {}
  },
  "135": {
    "name": "MVSep Clavinet",
    "priceCoefficient": 1,
    "outputs": {
      "clavinet": "Clavinet",
      "other": "Other"
    },
    "fields": {}
  },
  "136": {
    "name": "MVSep Mellotron",
    "priceCoefficient": 1,
    "outputs": {
      "mellotron": "Mellotron",
      "other": "Other"
    },
    "fields": {}
  },
  "138": {
    "name": "DeEffect vocals by gilliaan",
    "priceCoefficient": 1,
    "outputs": {},
    "fields": {}
  }
}
