// GENERATED by aurora-mcp/scripts/sync-separation.mjs from aurora/src/shared/separation/routes.ts. Do not edit: edit the app's file
// and run `node scripts/sync-separation.mjs`. `--check` (in npm run typecheck) fails on drift.
// Separation routes: which MVSEP model and options Aurora uses for each stem, and how each result is checked.
// The choices come from 50 measured test splits on clips mixed from true stems (2026-10-02); the evidence
// line on each route is the score that chose it (SDR in dB against the true stem; second-brain
// plans/2026-10-02-aurora-splitter-mvsep-research/stem-map.md). Pure data, shared by the app's main process,
// the renderer (labels, cost) and aurora-mcp (a byte-identical copy; tools/sync-separation-to-mcp.mjs).

export type RouteOptionName = 'add_opt1' | 'add_opt2' | 'add_opt3'

/** What a correct target sounds like next to what was left, measured without the true stems:
 *  percussive = more transient than the rest; low = more energy under 150 Hz than the rest;
 *  vocal = less energy under 150 Hz than the rest; none = no cheap test separates it. */
export type ContentFamily = 'percussive' | 'low' | 'vocal' | 'none'

/** How clean the measured result was (SDR against the true stem, 2026-10-02): good = 9 dB or more;
 *  fair = 5 to 9; rough = under 5 on the material it is for (orchestral sections overlap); untested = no
 *  measurement yet. Shown next to each part before a paid run. */
export type RouteQuality = 'good' | 'fair' | 'rough' | 'untested'

export interface SeparationRoute {
  /** Stable id: the MCP tools and the job log name routes by it. */
  id: string
  label: string
  sepType: number
  options: Partial<Record<RouteOptionName, string>>
  /** Aurora stem id → the exact MVSEP output key holding it. */
  delivers: Record<string, string>
  /** The checked target and what it is compared with. `complement` is an output key; without one the
   *  check compares the target with the input minus the target. */
  family: { target: string; complement?: string; family: ContentFamily }
  /** Outputs that must add back to a whole (another output, or the uploaded input). Each holds on every
   *  measured job of this route: one-model routes to about -150 dB, ensembles to -37 dB or better. */
  sums: { parts: string[]; whole: string | 'input' }[]
  /** The measured result that chose this route, or "not measured" with the research rank it rests on. */
  evidence: string
  quality: RouteQuality
}

const route = (r: SeparationRoute): SeparationRoute => r

// ── The 7-stem mastering split: three jobs. ───────────────────────────────────

export const SPLIT_ROUTES = {
  vocals: route({
    id: 'split-vocals',
    label: 'Vocals (BS Roformer 124 bands)',
    sepType: 40,
    options: { add_opt1: '171' },
    delivers: { vocals: 'vocals' },
    family: { target: 'vocals', complement: 'instrum', family: 'vocal' },
    sums: [{ parts: ['vocals', 'instrum'], whole: 'input' }],
    evidence: 'Vocals 11.4 dB (band), 3.8 (choir+orchestra); option 81 scored 3.7 on the same clip.',
    quality: 'good'
  }),
  drumsep: route({
    id: 'split-drumsep',
    label: 'Drum kit (DrumSep MelBand Roformer 6 stems)',
    sepType: 37,
    options: { add_opt1: '7', add_opt2: '0' },
    delivers: { kick: 'kick', snare: 'snare', toms: 'toms', drums_bus: 'drums' },
    family: { target: 'drums', family: 'percussive' },
    sums: [{ parts: ['kick', 'snare', 'toms', 'hh', 'ride', 'crash', 'residual'], whole: 'drums' }],
    evidence: 'Kick 12.8 dB, hats 11.4 (band); its drums bus is MVSep Drums option 6 (24.0 band).',
    quality: 'good'
  }),
  bass: route({
    id: 'split-bass',
    label: 'Bass (BS Roformer SW + SCNet XL)',
    sepType: 41,
    options: { add_opt1: '5', add_opt2: '0' },
    delivers: { bass: 'bass' },
    family: { target: 'bass', complement: 'other', family: 'low' },
    sums: [{ parts: ['bass', 'other'], whole: 'input' }],
    evidence: 'Bass 14.5 dB (band); BS Roformer SW 14.1, Mega 53 12.9.',
    quality: 'good'
  })
} satisfies Record<string, SeparationRoute>

// ── Extract: whole groups (one call each). ────────────────────────────────────

const group = (
  id: string,
  label: string,
  sepType: number,
  options: SeparationRoute['options'],
  key: string,
  complement: string,
  family: ContentFamily,
  quality: RouteQuality,
  evidence: string
): SeparationRoute =>
  route({
    id,
    label,
    sepType,
    options,
    delivers: { [id]: key },
    family: { target: key, complement, family },
    sums: [{ parts: [key, complement], whole: 'input' }],
    evidence,
    quality
  })

export const GROUP_ROUTES: Record<string, SeparationRoute> = {
  drums_full: group('drums_full', 'Drums (all)', 44, { add_opt1: '6', add_opt2: '0', add_opt3: '0' }, 'drums', 'other', 'percussive', 'good',
    'Drums 9.2 dB with pitched instruments under it, 5.5 full orchestra, 24.0 band; 96% of the file is percussion.'),
  percussion: group('percussion', 'Percussion', 105, {}, 'percussion', 'other', 'percussive', 'fair',
    'Percussion 7.3 dB / 4.7 orchestral: below Drums (all); includes pitched percussion by design.'),
  vocals_all: group('vocals_all', 'Vocals (all)', 40, { add_opt1: '171' }, 'vocals', 'instrum', 'vocal', 'good',
    'Vocals 11.4 dB (band); SW 9.7, Mega 9.0.'),
  choir: group('choir', 'Choir', 112, { add_opt2: '0' }, 'choir', 'other', 'vocal', 'rough',
    'Choir 3.8 dB under strings, brass and pads; 3.3 in the full orchestra; the file is 93% choir.'),
  brass: group('brass', 'Brass', 107, { add_opt1: '0' }, 'brass', 'other', 'none', 'rough',
    'Brass 2.1 dB (horn melody over strings), 2.0 full orchestra; the file is 77% brass. Weakest group route.'),
  woodwind: group('woodwind', 'Woodwinds', 108, { add_opt1: '0' }, 'woodwind', 'other', 'none', 'untested',
    'Not measured (no woodwinds in the test clips); the research rank-1 route.'),
  strings: group('strings', 'Strings (all)', 52, { add_opt1: '1', add_opt2: '0' }, 'strings', 'other', 'none', 'rough',
    'Strings 3.6 dB (with piano), 1.7 full orchestra; single string instruments score near 0.'),
  keys: group('keys', 'Keys (all)', 106, {}, 'keys', 'other', 'none', 'fair', 'Keys 5.5 dB (piano with strings).'),
  guitar: group('guitar', 'Guitars (all)', 31, { add_opt1: '7' }, 'guitar', 'other', 'none', 'fair', 'Guitar 8.1 dB (band).')
}

// ── Extract: single instruments and bundles (prism's catalog, now named by exact output keys). ──

/** A one-instrument route. `fromPart` routes run MVSEP's "Extract from <family> part" mode (`add_opt2=1`) and
 *  return four files: the target, `other-<family>` (the rest of that family), `all-<family>` and `no-<family>`.
 *  Measured exact on real jobs (2026-10-02, Brass from the wind part, Choir from the vocals): target +
 *  other-<family> = all-<family> (-211 dB) and all-<family> + no-<family> = the input (-153 dB). The family test
 *  compares the target with the input minus the target. */
const instrument = (
  id: string,
  sepType: number,
  key: string,
  options: SeparationRoute['options'] = {},
  { fromPart, family = 'none' as ContentFamily }: { fromPart?: 'wind' | 'strings' | 'guitar'; family?: ContentFamily } = {}
): SeparationRoute =>
  route({
    id,
    label: id,
    sepType,
    options: fromPart ? { ...options, add_opt2: '1' } : options,
    delivers: { [id]: key },
    family: fromPart ? { target: key, family } : { target: key, complement: 'other', family },
    sums: fromPart
      ? [
          { parts: [key, `other-${fromPart}`], whole: `all-${fromPart}` },
          { parts: [`all-${fromPart}`, `no-${fromPart}`], whole: 'input' }
        ]
      : [{ parts: [key, 'other'], whole: 'input' }],
    evidence: 'Not measured; carried over from prism.',
    quality: 'untested'
  })

const fromWind = { fromPart: 'wind' as const }
const fromStrings = { fromPart: 'strings' as const }
const fromGuitar = { fromPart: 'guitar' as const }

export const INSTRUMENT_ROUTES: Record<string, SeparationRoute> = {
  piano: { ...instrument('piano', 29, 'piano', { add_opt1: '5' }), evidence: 'Piano 5.7 dB (with strings); Keys 5.5, Mega 5.4.', quality: 'fair' },
  digital_piano: instrument('digital_piano', 79, 'digital-piano'),
  organ: instrument('organ', 58, 'organ', { add_opt1: '3' }),
  accordion: instrument('accordion', 99, 'accordion'),
  harpsichord: instrument('harpsichord', 91, 'harpsichord'),
  saxophone: instrument('saxophone', 61, 'saxophone', { add_opt1: '3' }),
  flute: instrument('flute', 67, 'flute', { add_opt1: '1' }, fromWind),
  trumpet: instrument('trumpet', 71, 'trumpet', {}, fromWind),
  trombone: instrument('trombone', 75, 'trombone', {}, fromWind),
  french_horn: instrument('french_horn', 82, 'french-horn', {}, fromWind),
  tuba: instrument('tuba', 92, 'tuba'),
  clarinet: instrument('clarinet', 78, 'clarinet', {}, fromWind),
  oboe: instrument('oboe', 77, 'oboe', {}, fromWind),
  bassoon: instrument('bassoon', 93, 'bassoon'),
  // Direct, not from the wind part: MVSEP has never recorded which files Harmonica's from-part mode returns.
  harmonica: instrument('harmonica', 87, 'harmonica'),
  guitar_acoustic: instrument('guitar_acoustic', 66, 'acoustic-guitar', {}, fromGuitar),
  guitar_electric: instrument('guitar_electric', 81, 'electric-guitar', {}, fromGuitar),
  mandolin: instrument('mandolin', 74, 'mandolin'),
  banjo: instrument('banjo', 83, 'banjo'),
  ukulele: instrument('ukulele', 96, 'ukulele'),
  harp: instrument('harp', 72, 'harp'),
  sitar: instrument('sitar', 90, 'sitar'),
  dobro: instrument('dobro', 97, 'dobro'),
  violin: instrument('violin', 65, 'violin'),
  viola: instrument('viola', 69, 'viola', {}, fromStrings),
  cello: instrument('cello', 70, 'cello', {}, fromStrings),
  double_bass: instrument('double_bass', 73, 'double-bass', {}, { fromPart: 'strings', family: 'low' }),
  bells: instrument('bells', 95, 'bells'),
  congas: instrument('congas', 94, 'congas', {}, { family: 'percussive' }),
  tambourine: instrument('tambourine', 76, 'tambourine', {}, { family: 'percussive' }),
  marimba: instrument('marimba', 84, 'marimba'),
  glockenspiel: instrument('glockenspiel', 85, 'glockenspiel'),
  timpani: instrument('timpani', 86, 'timpani'),
  triangle: instrument('triangle', 89, 'triangle'),
  wind_chimes: instrument('wind_chimes', 98, 'wind-chimes'),
  bass: { ...instrument('bass', 41, 'bass', { add_opt1: '5', add_opt2: '0' }, { family: 'low' }), evidence: 'Bass 14.5 dB (band).', quality: 'good' },
  synth: { ...instrument('synth', 88, 'synth', { add_opt1: '0' }), evidence: 'Synth 8.8 dB (band); fails under an orchestra (-1.8).', quality: 'fair' }
}

export const BUNDLE_ROUTES: Record<string, SeparationRoute> = {
  drumsep: route({
    id: 'drumsep',
    label: 'Drum Kit',
    sepType: 37,
    options: { add_opt1: '7', add_opt2: '0' },
    delivers: {
      drum_kick: 'kick',
      drum_snare: 'snare',
      drum_toms: 'toms',
      drum_hihats: 'hh',
      drum_cymbals_crash: 'crash',
      drum_cymbals_ride: 'ride'
    },
    family: { target: 'drums', family: 'percussive' },
    sums: [{ parts: ['kick', 'snare', 'toms', 'hh', 'ride', 'crash', 'residual'], whole: 'drums' }],
    evidence: 'Kick 12.8 dB, hats 11.4 (band).',
    quality: 'good'
  }),
  // add_opt2: 1 against the original mix, 0 against an already dry vocal (the planner sets it per run).
  lead_back_vocal: route({
    id: 'lead_back_vocal',
    label: 'Lead + Backing Vocals',
    sepType: 49,
    options: { add_opt1: '6', add_opt2: '1' },
    // Never `back-instrum`: it keeps the backing vocals by design.
    delivers: { vocal_lead: 'vocals-lead', vocal_back: 'vocals-back' },
    // Lead against backing is voice against voice: the low-end voice test does not apply.
    family: { target: 'vocals-lead', family: 'none' },
    // Measured exact on a real job (2026-10-02, band clip): backing + instrumental-only = back-instrum (-152 dB).
    sums: [{ parts: ['vocals-back', 'instrum-only'], whole: 'back-instrum' }],
    evidence: 'Lead + backing together 5.1 dB (band); backing alone about 0.',
    quality: 'fair'
  }),
  male_female_vocal: route({
    id: 'male_female_vocal',
    label: 'Male + Female Vocals',
    sepType: 57,
    options: { add_opt1: '3', add_opt2: '1' },
    // Never `instrumental-plus-male` / `instrumental-plus-female`: they keep a voice by design.
    delivers: { vocal_male: 'male', vocal_female: 'female' },
    family: { target: 'male', family: 'none' },
    sums: [],
    evidence: 'Not measured; carried over from prism.',
    quality: 'untested'
  }),
  lead_rhythm_guitar: route({
    id: 'lead_rhythm_guitar',
    label: 'Lead + Rhythm Guitar',
    sepType: 101,
    options: { add_opt1: '0' },
    delivers: { guitar_lead: 'lead-guitar', guitar_rhythm: 'rhythm-guitar' },
    family: { target: 'lead-guitar', family: 'none' },
    sums: [],
    evidence: 'Not measured; carried over from prism.',
    quality: 'untested'
  }),
  // BS Roformer dereverb (option 6). MelRoformer options return the wrong files through the API (prism).
  dereverb: route({
    id: 'dereverb',
    label: 'Dry + Reverb',
    sepType: 22,
    options: { add_opt1: '6', add_opt2: '0' },
    delivers: { vocal_dry: 'noreverb', vocal_reverb: 'reverb' },
    family: { target: 'noreverb', family: 'none' },
    sums: [],
    evidence: 'Not measured; carried over from prism.',
    quality: 'untested'
  })
}

/** Every route, by id. */
export const ALL_ROUTES: Record<string, SeparationRoute> = Object.fromEntries(
  [...Object.values(SPLIT_ROUTES), ...Object.values(GROUP_ROUTES), ...Object.values(INSTRUMENT_ROUTES), ...Object.values(BUNDLE_ROUTES)].map(
    (r) => [r.id, r]
  )
)
