// GENERATED by aurora-mcp/scripts/sync-separation.mjs from aurora/src/main/split/run-route.ts. Do not edit: edit the app's file
// and run `node scripts/sync-separation.mjs`. `--check` (in npm run typecheck) fails on drift.
import { randomUUID } from 'crypto'
import { join } from 'path'
import { rename, unlink, writeFile } from 'fs/promises'
import { decodeWav } from '../audio/wav.js'
import { resolveOutputs, OutputIdentityError } from './identify.js'
import { allFinite, checkRouteContent, type Channels, type CheckView, type ContentVerdict } from './content-check.js'
import type { SeparationRoute } from './routes.js'
import type { MvsepJobSpec, SeparationProvider, SeparationResult } from './contracts.js'

// One MVSEP job for one route, end to end, with its output checked before anything is saved: create (under
// a unique upload name), wait, resolve every file by its exact output key, download, check the audio
// (content-check.ts), and only then move each delivered stem to its final name. A failed check deletes the
// downloads and throws OutputIdentityError: a stem is never saved under a name it does not hold.
// runRoute does it all in one call. A caller that persists the job between steps (aurora-mcp's background
// jobs) uses the two halves: submitRoute (create; save the returned hash before waiting) and
// landRouteResult (given the finished result: resolve, download, check, save). checkLocalOutputs runs the
// same audio checks on files already on disk.
// Used by the 7-stem split, Extract, the bridge CLI and (as a generated mirror) aurora-mcp; relative
// imports, so it runs under plain tsx.

/** The family tests run on this much contiguous audio from the middle of the track (calibrated on 15 s
 *  clips); the sums and duplicate tests run on the same number of frames sampled across the WHOLE track, so
 *  damage outside the middle still shows. Both keep memory flat when DrumSep returns 8 files of a long track. */
const CHECK_WINDOW_SECONDS = 60

/** A stem download that has not finished in this long is abandoned (the job's result stays on MVSEP for 3 days). */
const DOWNLOAD_TIMEOUT_MS = 5 * 60_000

/** The same window of every file, placed by the input's length (MVSEP keeps length and timing). */
function windowOf(inputFrames: number, sampleRate: number): { start: number; len: number } {
  const len = Math.min(inputFrames, CHECK_WINDOW_SECONDS * sampleRate)
  return { start: Math.floor((inputFrames - len) / 2), len }
}

const excerpt = (chs: Channels, w: { start: number; len: number }): Channels =>
  chs.map((c) => c.slice(w.start, w.start + w.len))

/** Every `step`-th frame across the whole file: a track-wide sample at a bounded size. */
function strided(chs: Channels, step: number): Channels {
  if (step <= 1) return chs.map((c) => c.slice())
  return chs.map((c) => {
    const out = new Float32Array(Math.ceil(c.length / step))
    for (let i = 0, j = 0; i < c.length; i += step, j++) out[j] = c[i]
    return out
  })
}

const strideFor = (frames: number, sampleRate: number): number =>
  Math.max(1, Math.ceil(frames / (CHECK_WINDOW_SECONDS * sampleRate)))

/** The two views a check reads from one decoded file, plus whether every sample is a number. */
function views(chs: Channels, win: { start: number; len: number }, step: number): { middle: Channels; whole: Channels; finite: boolean } {
  return { middle: excerpt(chs, win), whole: strided(chs, step), finite: allFinite(chs) }
}

export interface RouteRun {
  /** MVSEP's job hash (for logs and manifests). */
  hash: string
  /** Delivered stem id → saved WAV path. */
  stems: Record<string, string>
  /** Extra outputs the caller asked to keep (`keep`), output key → saved path. */
  kept: Record<string, string>
  /** Non-fatal observations (a near-silent group). */
  notes: string[]
  /** The checks' measurements (sums, levels, family margins) and the window they ran on, in seconds. */
  metrics: Record<string, number>
  checkWindowSeconds: number
}

export interface SubmittedRoute {
  hash: string
  uploadName: string
  spec: MvsepJobSpec
}

export interface RunRouteOptions {
  route: SeparationRoute
  /** Exactly the bytes uploaded (the checks compare the outputs with this). */
  input: Buffer
  destDir: string
  /** Final file name per delivered stem id; defaults to `<stemId>.wav`. */
  fileNames?: Record<string, string>
  /** Option values that override the route's for this run (lead/back on a dry vocal: add_opt2=0). */
  optionOverrides?: Partial<MvsepJobSpec>
  /** Output keys to keep beyond the delivered stems (the DrumSep drums bus), saved as `<key>.wav`. */
  keep?: string[]
  onStatus?: (status: string) => void
}

/** The create-call spec for a route: 32-bit float WAV (the sums and Other phase-cancel need it), its options,
 *  then any overrides. */
export function routeSpec(route: SeparationRoute, overrides?: Partial<MvsepJobSpec>): MvsepJobSpec {
  return { sep_type: String(route.sepType), output_format: '4', is_demo: '0', ...route.options, ...overrides }
}

/** Every output key a route reads: what it delivers, what its checks compare, what the caller keeps. */
export function routeOutputKeys(route: SeparationRoute, keep: string[] = []): string[] {
  return [
    ...new Set([
      ...Object.values(route.delivers),
      route.family.target,
      ...(route.family.complement ? [route.family.complement] : []),
      ...route.sums.flatMap((s) => [...s.parts, ...(s.whole === 'input' ? [] : [s.whole])]),
      ...keep
    ])
  ]
}

/** Create the job under a unique upload name. Save the returned hash before waiting on it. */
export async function submitRoute(
  provider: SeparationProvider,
  opts: Pick<RunRouteOptions, 'route' | 'input' | 'optionOverrides'>
): Promise<SubmittedRoute> {
  const spec = routeSpec(opts.route, opts.optionOverrides)
  const uploadName = `aurora-${opts.route.id}-${randomUUID().slice(0, 8)}.wav`
  const { hash } = await provider.createJob(opts.input, spec, uploadName)
  return { hash, uploadName, spec }
}

/** The audio checks on outputs already on disk: `outputs` maps output key → WAV bytes. */
export function checkLocalOutputs(
  route: SeparationRoute,
  input: Buffer,
  outputs: Record<string, Buffer>
): ContentVerdict & { checkWindowSeconds: number } {
  const wav = decodeWav(input)
  const win = windowOf(wav.frames, wav.sampleRate)
  const step = strideFor(wav.frames, wav.sampleRate)
  const middle: Record<string, Channels> = {}
  const whole: CheckView = { input: strided(wav.channels, step), outputs: {} }
  for (const [key, buf] of Object.entries(outputs)) {
    const v = views(decodeWav(buf).channels, win, step)
    middle[key] = v.middle
    whole.outputs[key] = v.whole
  }
  return {
    ...checkRouteContent(route, excerpt(wav.channels, win), middle, wav.sampleRate, undefined, whole),
    checkWindowSeconds: win.len / wav.sampleRate
  }
}

/** Given a finished job's result: resolve every file, download, check, and save the delivered stems. */
export async function landRouteResult(
  hash: string,
  result: SeparationResult,
  opts: Omit<RunRouteOptions, 'onStatus'>
): Promise<RouteRun> {
  const { route, input, destDir } = opts
  const needed = routeOutputKeys(route, opts.keep)
  const { byKey } = resolveOutputs(route.sepType, result.files, needed, result.algorithm)

  // Keep only the window of the decoded input: three split jobs run at once on the same track.
  const { win, step, inputWindow, inputWhole, sampleRate, inputFrames, inputChannels } = (() => {
    const wav = decodeWav(input)
    const w = windowOf(wav.frames, wav.sampleRate)
    const st = strideFor(wav.frames, wav.sampleRate)
    return {
      win: w,
      step: st,
      inputWindow: excerpt(wav.channels, w),
      inputWhole: strided(wav.channels, st),
      sampleRate: wav.sampleRate,
      inputFrames: wav.frames,
      inputChannels: wav.channels.length
    }
  })()

  // Download every needed output under a temporary name. allSettled, not all: a failed download must not
  // leave a sibling still writing after the cleanup below has run.
  const tmp: Record<string, string> = {}
  const audio: Record<string, Channels> = {}
  const wholeTrack: CheckView = { input: inputWhole, outputs: {} }
  const tag = randomUUID().slice(0, 8)
  try {
    const settled = await Promise.allSettled(
      needed.map(async (key) => {
        const res = await fetch(byKey[key].url, { signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS) })
        if (!res.ok) throw new Error(`Stem download failed (HTTP ${res.status}): ${byKey[key].filename}`)
        const buf = Buffer.from(await res.arrayBuffer())
        tmp[key] = join(destDir, `.${tag}-${key}.unverified.wav`)
        await writeFile(tmp[key], buf)
        const wav = decodeWav(buf)
        // MVSEP's models keep rate, length and channels; a file that does not is not this job's stem.
        if (wav.sampleRate !== sampleRate || wav.channels.length !== inputChannels || Math.abs(wav.frames - inputFrames) > 1) {
          throw new OutputIdentityError(
            `${route.label}: "${key}" is ${wav.sampleRate} Hz, ${wav.channels.length} ch, ${wav.frames} frames; ` +
              `the input is ${sampleRate} Hz, ${inputChannels} ch, ${inputFrames} frames. Nothing was saved.`
          )
        }
        const v = views(wav.channels, win, step)
        if (!v.finite) {
          throw new OutputIdentityError(`${route.label}: "${key}" contains samples that are not numbers (NaN or infinity). Nothing was saved.`)
        }
        audio[key] = v.middle
        wholeTrack.outputs[key] = v.whole
      })
    )
    const failed = settled.find((s): s is PromiseRejectedResult => s.status === 'rejected')
    if (failed) throw failed.reason
    const verdict = checkRouteContent(route, inputWindow, audio, sampleRate, undefined, wholeTrack)
    if (!verdict.ok) {
      throw new OutputIdentityError(
        `${route.label}: the result failed its check, so nothing was saved. ${verdict.problems.join('. ')}.`
      )
    }

    const stems: Record<string, string> = {}
    for (const [stemId, key] of Object.entries(route.delivers)) {
      const dest = join(destDir, opts.fileNames?.[stemId] ?? `${stemId}.wav`)
      await rename(tmp[key], dest)
      delete tmp[key]
      stems[stemId] = dest
    }
    const kept: Record<string, string> = {}
    for (const key of opts.keep ?? []) {
      if (!tmp[key]) continue
      kept[key] = join(destDir, `${key}.wav`)
      await rename(tmp[key], kept[key])
      delete tmp[key]
    }
    return { hash, stems, kept, notes: verdict.notes, metrics: verdict.metrics, checkWindowSeconds: win.len / sampleRate }
  } finally {
    await Promise.all(Object.values(tmp).map((p) => unlink(p).catch(() => {})))
  }
}

/** The whole job in one call: submit, wait, land. */
export async function runRoute(provider: SeparationProvider, opts: RunRouteOptions): Promise<RouteRun> {
  const { hash } = await submitRoute(provider, opts)
  const result = await provider.awaitResult({ hash }, opts.onStatus)
  return landRouteResult(hash, result, opts)
}
