// GENERATED by aurora-mcp/scripts/sync-separation.mjs from aurora/src/shared/extract-catalog.ts. Do not edit: edit the app's file
// and run `node scripts/sync-separation.mjs`. `--check` (in npm run typecheck) fails on drift.
// Sample Extractor catalog + call planning. The separation routes (which MVSEP model and options per stem,
// and the exact output key each stem comes from) live in ./separation/routes.ts, chosen from measured test
// splits; this module turns an orb selection into the call plan and the cost card. Pure logic, no IO:
// shared by the main-process orchestrator AND the renderer cost card.
//
// LOCKSTEP: aurora-mcp/packages/shared/src/extract-catalog.ts is an identical copy (storage-semantics
// lockstep rule). Behavior changes go into BOTH files or neither.

import { ALL_ROUTES, BUNDLE_ROUTES, GROUP_ROUTES, INSTRUMENT_ROUTES, type SeparationRoute } from './separation/routes.js'

export interface ExtractBundleConfig {
  stems: string[]
  sepType: number
  addOpt1?: number
  addOpt2?: number
  routeId: string
}

const optNum = (r: SeparationRoute, name: 'add_opt1' | 'add_opt2'): number | undefined =>
  r.options[name] === undefined ? undefined : Number(r.options[name])

const bundle = (r: SeparationRoute): ExtractBundleConfig => ({
  stems: Object.keys(r.delivers),
  sepType: r.sepType,
  addOpt1: optNum(r, 'add_opt1'),
  addOpt2: optNum(r, 'add_opt2'),
  routeId: r.id
})

// Bundled stems: one MVSEP call returns several stems.
export const EXTRACT_BUNDLES: Record<string, ExtractBundleConfig> = Object.fromEntries(
  Object.entries(BUNDLE_ROUTES).map(([id, r]) => [id, bundle(r)])
)

export interface IndividualStemConfig {
  sepType: number
  addOpt1?: number
  addOpt2?: number
  /** The exact MVSEP output key holding this stem. */
  mvsepName: string
  routeId: string
}

const single = (r: SeparationRoute): IndividualStemConfig => ({
  sepType: r.sepType,
  addOpt1: optNum(r, 'add_opt1'),
  addOpt2: optNum(r, 'add_opt2'),
  mvsepName: Object.values(r.delivers)[0],
  routeId: r.id
})

// One MVSEP call per stem: whole groups (drums, choir, brass, strings...) and single instruments.
export const EXTRACT_INDIVIDUAL_STEMS: Record<string, IndividualStemConfig> = Object.fromEntries(
  [...Object.entries(GROUP_ROUTES), ...Object.entries(INSTRUMENT_ROUTES)].map(([id, r]) => [id, single(r)])
)

/** Group stems (one model for a whole family) shown first in the orb and in the cost card. */
export const GROUP_STEM_IDS = new Set(Object.keys(GROUP_ROUTES))

/** Vocal stems are driven by vocalMode/includeReverb, never by direct selection. */
export const VOCAL_STEM_IDS = new Set([
  'vocal_lead',
  'vocal_back',
  'vocal_male',
  'vocal_female',
  'vocal_dry',
  'vocal_reverb'
])

export type VocalSeparationType = 'lead_back' | 'male_female' | null

export interface ExtractSelection {
  /** Non-vocal stem ids (orb selection). Category markers are filtered upstream. */
  stems: string[]
  vocalSeparationType: VocalSeparationType
  includeReverb: boolean
}

export interface PlannedApiCall {
  type: 'dereverb' | 'vocal_bundle' | 'bundle' | 'individual'
  /** bundle/vocal_bundle: EXTRACT_BUNDLES key. individual: the stem id. */
  id: string
  /** The separation route (./separation/routes.ts ALL_ROUTES key) this call runs. */
  routeId: string
  sepType: number
  addOpt1?: number
  addOpt2?: number
  /** 'original' | 'dry' — dry chains the dereverbed vocal into a vocal bundle. */
  inputSource: 'original' | 'dry'
  /** What the progress line calls this call. */
  outputType: string
  /** dereverb only: deliver vocal_dry as a stem (reverb-only mode, no vocal bundle). */
  deliverVocalDry?: boolean
}

export interface ExtractPlan {
  calls: PlannedApiCall[]
  /** Stem ids this run delivers (ALWAYS ends with 'other' — free, local, undeselectable). */
  stemsToDeliver: string[]
}

/** Port of sample_worker.plan_api_calls — convert a selection into the
 *  optimized MVSEP call plan. Other is always delivered (local phase-cancel). */
export function planApiCalls(selection: ExtractSelection): ExtractPlan {
  const calls: PlannedApiCall[] = []
  const stemsToDeliver: string[] = []
  let dereverbRan = false

  // Step 0: dereverb. Always BS Roformer (add_opt1=6): MelRoformer options return the wrong files through
  // the API (prism).
  if (selection.includeReverb) {
    const deliverVocalDry = selection.vocalSeparationType === null
    calls.push({
      type: 'dereverb',
      id: 'dereverb',
      routeId: 'dereverb',
      sepType: 22,
      addOpt1: 6,
      addOpt2: 0,
      inputSource: 'original',
      outputType: 'dereverb',
      deliverVocalDry
    })
    stemsToDeliver.push('vocal_reverb')
    if (deliverVocalDry) stemsToDeliver.push('vocal_dry')
    dereverbRan = true
  }

  // Step 1: vocal separation bundle.
  if (selection.vocalSeparationType) {
    const bundleId =
      selection.vocalSeparationType === 'lead_back' ? 'lead_back_vocal' : 'male_female_vocal'
    const bundle = EXTRACT_BUNDLES[bundleId]
    calls.push({
      type: 'vocal_bundle',
      id: bundleId,
      routeId: bundle.routeId,
      sepType: bundle.sepType,
      addOpt1: bundle.addOpt1,
      // add_opt2: 1 against the original, 0 against the dereverbed dry vocal.
      addOpt2: dereverbRan ? 0 : 1,
      inputSource: dereverbRan ? 'dry' : 'original',
      outputType: selection.vocalSeparationType
    })
    stemsToDeliver.push(...bundle.stems)
  }

  // Step 2: non-vocal bundles (drums, guitars) — any selected member pulls the
  // whole bundle in ONE call.
  const covered = new Set<string>()
  for (const bundleId of ['drumsep', 'lead_rhythm_guitar'] as const) {
    const bundle = EXTRACT_BUNDLES[bundleId]
    const requested = bundle.stems.filter((s) => selection.stems.includes(s))
    if (requested.length > 0) {
      calls.push({
        type: 'bundle',
        id: bundleId,
        routeId: bundle.routeId,
        sepType: bundle.sepType,
        addOpt1: bundle.addOpt1,
        addOpt2: bundle.addOpt2,
        inputSource: 'original',
        outputType: bundleId,
        // prism delivered the full bundle; we keep that (you paid for the call).
      })
      stemsToDeliver.push(...bundle.stems)
      for (const s of bundle.stems) covered.add(s)
    }
  }

  // Step 3: individual stems.
  for (const stemId of selection.stems) {
    if (!covered.has(stemId) && EXTRACT_INDIVIDUAL_STEMS[stemId]) {
      const cfg = EXTRACT_INDIVIDUAL_STEMS[stemId]
      calls.push({
        type: 'individual',
        id: stemId,
        routeId: cfg.routeId,
        sepType: cfg.sepType,
        addOpt1: cfg.addOpt1,
        addOpt2: cfg.addOpt2,
        inputSource: 'original',
        outputType: stemId
      })
      stemsToDeliver.push(stemId)
    }
  }

  // Other is always generated and delivered (free, local).
  stemsToDeliver.push('other')

  return { calls, stemsToDeliver }
}

// ── Cost math (port of credits-calculator.ts, extraction half) ──────────────
// Aurora's new credit model meters cloud calls; pack pricing is deferred, so
// the DISPLAY unit today is real provider units: MVSEP calls × ceil(minutes).
// The 10-credits/min/call constant survives for the future pack metering.

export const CREDITS_PER_MINUTE = 10

/** 0-1 min = 1x, 1-2 min = 2x, … */
export function getMinuteMultiplier(durationSeconds: number): number {
  if (durationSeconds <= 0) return 1
  return Math.ceil(durationSeconds / 60)
}

export interface ExtractCallBreakdown {
  bundles: { bundleId: string; stems: string[] }[]
  individualStems: string[]
  totalCalls: number
}

/** Breakdown for the cost card — derived from the REAL plan, so the count can
 *  never drift from what the orchestrator fires. */
export function getCallBreakdown(selection: ExtractSelection): ExtractCallBreakdown {
  const plan = planApiCalls(selection)
  const bundles: { bundleId: string; stems: string[] }[] = []
  const individualStems: string[] = []
  for (const call of plan.calls) {
    if (call.type === 'individual') individualStems.push(call.id)
    else bundles.push({ bundleId: call.id, stems: EXTRACT_BUNDLES[call.id]?.stems ?? [] })
  }
  return { bundles, individualStems, totalCalls: plan.calls.length }
}

export function countApiCalls(selection: ExtractSelection): number {
  return planApiCalls(selection).calls.length
}

export interface ExtractCostEstimate {
  totalCalls: number
  minuteMultiplier: number
  /** Future pack metering: calls × minutes × CREDITS_PER_MINUTE. */
  credits: number
  breakdown: ExtractCallBreakdown
}

export function estimateExtractCost(
  selection: ExtractSelection,
  durationSeconds: number = 60
): ExtractCostEstimate {
  const breakdown = getCallBreakdown(selection)
  const minuteMultiplier = getMinuteMultiplier(durationSeconds)
  return {
    totalCalls: breakdown.totalCalls,
    minuteMultiplier,
    credits: breakdown.totalCalls * minuteMultiplier * CREDITS_PER_MINUTE,
    breakdown
  }
}

/** The route a cost-card row runs (a bundle id or a stem id): its measured quality and evidence. */
export function routeForCostRow(id: string): SeparationRoute | undefined {
  const routeId = EXTRACT_BUNDLES[id]?.routeId ?? EXTRACT_INDIVIDUAL_STEMS[id]?.routeId
  return routeId ? ALL_ROUTES[routeId] : undefined
}

// Human-readable bundle names for cost cards.
export const BUNDLE_DISPLAY_NAMES: Record<string, string> = {
  drumsep: 'Drum Kit',
  dereverb: 'Dry + Reverb',
  lead_back_vocal: 'Lead + Backing Vocals',
  male_female_vocal: 'Male + Female Vocals',
  lead_rhythm_guitar: 'Lead + Rhythm Guitar'
}

/** Display labels for every extractable stem id (orb names + vocal modes). */
export const EXTRACT_STEM_LABELS: Record<string, string> = {
  ...Object.fromEntries(Object.values(GROUP_ROUTES).map((r) => [r.id, r.label])),
  vocal_lead: 'Lead Vocal',
  vocal_back: 'Backing Vocals',
  vocal_male: 'Male Vocal',
  vocal_female: 'Female Vocal',
  vocal_dry: 'Dry Vocal',
  vocal_reverb: 'Reverb Tail',
  drum_kick: 'Kick',
  drum_snare: 'Snare',
  drum_toms: 'Toms',
  drum_hihats: 'Hi-Hats',
  drum_cymbals_crash: 'Crash',
  drum_cymbals_ride: 'Ride',
  guitar_lead: 'Lead Guitar',
  guitar_rhythm: 'Rhythm Guitar',
  guitar_acoustic: 'Acoustic Guitar',
  guitar_electric: 'Electric Guitar',
  piano: 'Piano',
  digital_piano: 'Digital Piano',
  organ: 'Organ',
  accordion: 'Accordion',
  harpsichord: 'Harpsichord',
  saxophone: 'Saxophone',
  flute: 'Flute',
  trumpet: 'Trumpet',
  trombone: 'Trombone',
  french_horn: 'French Horn',
  tuba: 'Tuba',
  clarinet: 'Clarinet',
  oboe: 'Oboe',
  bassoon: 'Bassoon',
  harmonica: 'Harmonica',
  mandolin: 'Mandolin',
  banjo: 'Banjo',
  ukulele: 'Ukulele',
  harp: 'Harp',
  sitar: 'Sitar',
  dobro: 'Dobro',
  violin: 'Violin',
  viola: 'Viola',
  cello: 'Cello',
  double_bass: 'Double Bass',
  bells: 'Bells',
  congas: 'Congas',
  tambourine: 'Tambourine',
  marimba: 'Marimba',
  glockenspiel: 'Glockenspiel',
  timpani: 'Timpani',
  triangle: 'Triangle',
  wind_chimes: 'Wind Chimes',
  bass: 'Bass',
  synth: 'Synth',
  other: 'Other'
}

/** Upload/duration caps — prism's cost protection, adopted. */
export const EXTRACT_MAX_DURATION_SECONDS = 12 * 60
