// GENERATED by aurora-mcp/scripts/sync-separation.mjs from aurora/src/shared/recipe.ts. Do not edit: edit the app's file
// and run `node scripts/sync-separation.mjs`. `--check` (in npm run typecheck) fails on drift.
// The recipe: what made an asset or a stem, stored with it at creation and
// reusable from it. One source for the app and the MCP: aurora-mcp mirrors this
// file through scripts/sync-separation.mjs, so it imports nothing.
//
// Plan: second-brain plans/2026-10-07-aurora-recipe-and-reuse.md.

export const RECIPE_VERSION = 1

export type RecipeOperation =
  | 'generate'
  | 'sounds'
  | 'cover'
  | 'add-vocals'
  | 'add-instrumental'
  | 'extend'
  | 'replace-section'
  | 'mashup'
  | 'import'
  | 'master'
  | 'split'
  | 'extract'
  | 'stem-import'
  | 'stem-set'
  | 'pitch-shift'
  | 'convert'
  | 'unknown'

export type RecipeProvider = 'sunoapi' | 'kie' | 'ace-step' | 'mvsep' | 'local'

export interface RecipeInput {
  /** source: the audio a transform worked on. reference: a match or style
   *  reference. mashup-b: the second track of a mashup. upload: a file from
   *  outside the project. */
  role: 'source' | 'reference' | 'mashup-b' | 'upload'
  assetId?: string | null
  path?: string | null
  name?: string | null
}

export interface RecipeLineage {
  relation:
    | 'cover-of'
    | 'layered-on'
    | 'extended-from'
    | 'edited-from'
    | 'mashup-of'
    | 'split-from'
    | 'extracted-from'
    | 'mastered-from'
    | 'stems-of'
    | 'derived-from'
  assetId: string
}

export interface RecipeCredits {
  provider: RecipeProvider
  /** Null when the price is not known. */
  amount: number | null
  unit: 'suno-credits' | 'mvsep-minutes' | 'none'
  /** price-table: the measured per-call price below; estimate: computed from
   *  the route and duration before the call; none: a free local operation. */
  basis: 'price-table' | 'estimate' | 'none' | 'unknown'
}

export interface Recipe {
  v: number
  operation: RecipeOperation
  provider?: RecipeProvider | null
  model?: string | null
  /** Provider-side model or route version, when it differs from `model`. */
  modelVersion?: string | null
  /** The words as typed. In custom mode the lyrics; otherwise the description. */
  prompt?: string | null
  style?: string | null
  title?: string | null
  instrumental?: boolean | null
  customMode?: boolean | null
  /** Every other parameter as it was sent, by its wire name. */
  settings: Record<string, unknown>
  inputs: RecipeInput[]
  lineage: RecipeLineage[]
  credits?: RecipeCredits | null
  createdAt: number
  recordedBy: 'app' | 'mcp' | 'backfill'
  /** Backfilled recipes only: what the stored data could not recover. */
  missing?: string[]
}

// ── Measured prices ─────────────────────────────────────────────────────────
// sunoapi.org credits per call, measured 2026-06-10 (receipt: aurora-mcp
// skills/aurora-cost-discipline.md § Known costs). A null price is not yet
// measured; the recipe then says so rather than guessing.
const SUNO_PRICE: Partial<Record<RecipeOperation, number | null>> = {
  sounds: 2.5,
  cover: 12,
  generate: null,
  'add-vocals': null,
  'add-instrumental': null,
  extend: null,
  'replace-section': null,
  mashup: null
}

const LOCAL_OPERATIONS: RecipeOperation[] = ['import', 'master', 'stem-import', 'stem-set', 'pitch-shift', 'convert']

export function creditsFor(operation: RecipeOperation, provider?: RecipeProvider | null): RecipeCredits {
  if (LOCAL_OPERATIONS.includes(operation)) return { provider: 'local', amount: 0, unit: 'none', basis: 'none' }
  if (operation in SUNO_PRICE) {
    const amount = SUNO_PRICE[operation] ?? null
    return { provider: provider ?? 'sunoapi', amount, unit: 'suno-credits', basis: amount === null ? 'unknown' : 'price-table' }
  }
  if (operation === 'split' || operation === 'extract') return { provider: 'mvsep', amount: null, unit: 'mvsep-minutes', basis: 'unknown' }
  return { provider: provider ?? 'local', amount: null, unit: 'none', basis: 'unknown' }
}

// ── Building one at creation ────────────────────────────────────────────────

/** The generation fields of a stored origin (GenerationMeta and the MCP's
 *  job params): the words, the model and the named settings. */
const WORD_KEYS = ['prompt', 'style', 'title', 'instrumental', 'customMode', 'model', 'provider'] as const
/** Per-variation and storage facts: kept in the origin, never part of the recipe. */
const NOT_SETTINGS = new Set<string>([
  ...WORD_KEYS,
  'taskId',
  'audioId',
  'artworkPath',
  'durationSeconds',
  'tags',
  'sourceAssetId',
  'sourcePath',
  'sourceAssetIdB',
  'sourcePathB',
  'tool',
  'recipe',
  'op',
  'operation',
  'route',
  'sourceB',
  'projectId',
  'trackId',
  'baseName',
  'wait',
  'background',
  'confirm',
  'estimateOnly'
])

function isRecord(v: unknown): v is Record<string, unknown> {
  return !!v && typeof v === 'object' && !Array.isArray(v)
}

function str(v: unknown): string | null {
  return typeof v === 'string' && v.length > 0 ? v : null
}

function bool(v: unknown): boolean | null {
  return typeof v === 'boolean' ? v : null
}

function settingsOf(params: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(params)) {
    if (NOT_SETTINGS.has(k) || v === undefined) continue
    out[k] = v
  }
  return out
}

const LINEAGE_FOR: Partial<Record<RecipeOperation, RecipeLineage['relation']>> = {
  cover: 'cover-of',
  'add-vocals': 'layered-on',
  'add-instrumental': 'layered-on',
  extend: 'extended-from',
  'replace-section': 'edited-from',
  mashup: 'mashup-of',
  split: 'split-from',
  extract: 'extracted-from',
  master: 'mastered-from',
  'stem-import': 'stems-of',
  'stem-set': 'stems-of',
  'pitch-shift': 'derived-from',
  convert: 'derived-from'
}

export interface GenerationRecipeArgs {
  operation: RecipeOperation
  /** The request as sent: GenerationMeta or the MCP job's params. */
  params: Record<string, unknown>
  recordedBy: 'app' | 'mcp'
  sourceAssetId?: string | null
  sourcePath?: string | null
  /** Mashup's second track. */
  sourceAssetIdB?: string | null
  sourcePathB?: string | null
  createdAt?: number
}

/** The recipe of a Suno generation, sound or transform, from its request. */
export function generationRecipe(a: GenerationRecipeArgs): Recipe {
  const p = a.params
  const inputs: RecipeInput[] = []
  const lineage: RecipeLineage[] = []
  const sourceId = a.sourceAssetId ?? str(p.sourceAssetId)
  const sourcePath = a.sourcePath ?? str(p.sourcePath)
  if (sourceId || sourcePath) inputs.push({ role: sourceId ? 'source' : 'upload', assetId: sourceId, path: sourcePath })
  const relation = LINEAGE_FOR[a.operation]
  if (sourceId && relation) lineage.push({ relation, assetId: sourceId })
  // Older MCP mashups stored the second track as `sourceB`: an asset id or a file path.
  const legacyB = str(p.sourceB)
  const legacyBIsPath = !!legacyB && /[\\/]/.test(legacyB)
  const bId = a.sourceAssetIdB ?? str(p.sourceAssetIdB) ?? (legacyB && !legacyBIsPath ? legacyB : null)
  const bPath = a.sourcePathB ?? str(p.sourcePathB) ?? (legacyBIsPath ? legacyB : null)
  if (bId || bPath) inputs.push({ role: 'mashup-b', assetId: bId, path: bPath })
  if (bId && a.operation === 'mashup') lineage.push({ relation: 'mashup-of', assetId: bId })
  const provider = (str(p.provider) as RecipeProvider | null) ?? 'sunoapi'
  return {
    v: RECIPE_VERSION,
    operation: a.operation,
    provider,
    model: str(p.model),
    prompt: typeof p.prompt === 'string' ? p.prompt : null,
    style: str(p.style) ?? str(p.tags),
    title: str(p.title),
    instrumental: bool(p.instrumental),
    customMode: bool(p.customMode),
    settings: settingsOf(p),
    inputs,
    lineage,
    credits: creditsFor(a.operation, provider),
    createdAt: a.createdAt ?? Date.now(),
    recordedBy: a.recordedBy
  }
}

export interface LocalRecipeArgs {
  operation: RecipeOperation
  recordedBy: 'app' | 'mcp'
  provider?: RecipeProvider
  model?: string | null
  modelVersion?: string | null
  settings?: Record<string, unknown>
  inputs?: RecipeInput[]
  /** The asset this one came from; its lineage relation follows the operation. */
  fromAssetId?: string | null
  credits?: RecipeCredits | null
  createdAt?: number
}

/** The recipe of an import, master, split, extraction, stem set or local transform. */
export function localRecipe(a: LocalRecipeArgs): Recipe {
  const relation = LINEAGE_FOR[a.operation]
  return {
    v: RECIPE_VERSION,
    operation: a.operation,
    provider: a.provider ?? 'local',
    model: a.model ?? null,
    modelVersion: a.modelVersion ?? null,
    settings: a.settings ?? {},
    inputs: a.inputs ?? [],
    lineage: a.fromAssetId && relation ? [{ relation, assetId: a.fromAssetId }] : [],
    credits: a.credits === undefined ? creditsFor(a.operation, a.provider) : a.credits,
    createdAt: a.createdAt ?? Date.now(),
    recordedBy: a.recordedBy
  }
}

// ── Reading one back ────────────────────────────────────────────────────────

/** A stored recipe column, or null when it is absent or not a recipe. */
export function parseRecipe(json: unknown): Recipe | null {
  if (json == null) return null
  let v: unknown = json
  if (typeof json === 'string') {
    try {
      v = JSON.parse(json)
    } catch {
      return null
    }
  }
  if (!isRecord(v) || typeof v.operation !== 'string' || typeof v.v !== 'number') return null
  return {
    ...(v as unknown as Recipe),
    settings: isRecord(v.settings) ? v.settings : {},
    inputs: Array.isArray(v.inputs) ? (v.inputs as RecipeInput[]) : [],
    lineage: Array.isArray(v.lineage) ? (v.lineage as RecipeLineage[]) : []
  }
}

export interface AssetRowForRecipe {
  kind: string
  origin: unknown
  sourceAssetId?: string | null
  refId?: string | null
  createdAt: number
  path?: string
}

function parseOrigin(origin: unknown): Record<string, unknown> | null {
  if (typeof origin === 'string') {
    try {
      const v = JSON.parse(origin)
      return isRecord(v) ? v : null
    } catch {
      return null
    }
  }
  return isRecord(origin) ? origin : null
}

/** Which Suno operation a stored origin came from. The app's origin never
 *  named it, so this reads the fields only one operation writes. */
function inferOperation(kind: string, o: Record<string, unknown>): { op: RecipeOperation; guessed: boolean } {
  if (typeof o.operation === 'string') return { op: o.operation as RecipeOperation, guessed: false }
  // MCP builds before recipes stored the operation as `op`, with underscores.
  if (typeof o.op === 'string' && LEGACY_OPS.includes(o.op)) return { op: o.op.replace(/_/g, '-') as RecipeOperation, guessed: false }
  if (o.tool === 'pitch_shift') return { op: 'pitch-shift', guessed: false }
  if (o.tool === 'convert') return { op: 'convert', guessed: false }
  if ('soundKey' in o || 'soundTempo' in o || 'soundLoop' in o) return { op: 'sounds', guessed: false }
  if ('continueAt' in o || 'defaultParamFlag' in o) return { op: 'extend', guessed: false }
  if ('infillStartS' in o || 'infillEndS' in o) return { op: 'replace-section', guessed: false }
  if ('sourceAssetIdB' in o || 'sourcePathB' in o || 'uploadUrlB' in o || 'sourceB' in o) return { op: 'mashup', guessed: false }
  if (kind === 'cover') return { op: 'cover', guessed: true }
  return { op: 'generate', guessed: kind !== 'generation' }
}

/**
 * The recipe an existing asset row can support, from what was stored before
 * recipes existed: the origin JSON, `source_asset_id` and the row's kind.
 * `missing` names what could not be recovered, so the panel can say so.
 */
export function deriveAssetRecipe(row: AssetRowForRecipe): Recipe {
  const o = parseOrigin(row.origin)
  const base = { createdAt: row.createdAt }
  if (o && ('provider' in o || 'prompt' in o || 'tool' in o)) {
    const { op, guessed } = inferOperation(row.kind, o)
    if (op === 'pitch-shift' || op === 'convert') {
      const r = localRecipe({ operation: op, recordedBy: 'app', settings: settingsOf(o), fromAssetId: row.sourceAssetId ?? str(o.sourceAssetId), ...base })
      return { ...r, recordedBy: 'backfill', missing: [] }
    }
    const r = generationRecipe({ operation: op, params: o, recordedBy: 'app', sourceAssetId: row.sourceAssetId ?? null, ...base })
    // The cost line already says when the price was not measured.
    const missing: string[] = []
    if (guessed) missing.unshift('which Suno operation (read as ' + op + ')')
    if ((op === 'cover' || op === 'add-vocals' || op === 'add-instrumental') && !row.sourceAssetId && !str(o.sourcePath)) {
      missing.push('the source audio')
    }
    return { ...r, recordedBy: 'backfill', missing }
  }
  if (row.kind === 'master') {
    const r = localRecipe({ operation: 'master', recordedBy: 'app', fromAssetId: row.sourceAssetId ?? null, ...base })
    return { ...r, recordedBy: 'backfill', missing: ['the track it was mastered from', 'the reference', 'the mastering settings'].slice(row.sourceAssetId ? 1 : 0) }
  }
  if (row.kind === 'track') {
    const r = localRecipe({ operation: 'import', recordedBy: 'app', fromAssetId: row.sourceAssetId ?? null, ...base })
    return { ...r, recordedBy: 'backfill', missing: ['the original file path'] }
  }
  const r = localRecipe({ operation: 'unknown', recordedBy: 'app', fromAssetId: row.sourceAssetId ?? null, credits: null, ...base })
  return { ...r, recordedBy: 'backfill', missing: ['everything: nothing was stored when it was made'] }
}

export interface StemRowForRecipe {
  /** project_stems: split; extraction_stems: extract; stem_sets: stem-set or stem-import. */
  table: 'project_stems' | 'extraction_stems' | 'stem_sets'
  assetId: string
  /** project_stems.origin, stem_sets.kind. */
  origin?: string | null
  stemKey?: string | null
  sourcePath?: string | null
  createdAt?: number | null
  /** stem_sets imported from a bridge split: its job.json, when it is still on disk. */
  job?: unknown
}

/** The settings a bridge split's job.json records: its options and which MVSEP
 *  jobs it ran. The input and output paths are the recipe's inputs, not settings. */
export function splitJobSettings(job: unknown): Record<string, unknown> {
  if (!isRecord(job)) return {}
  const args = isRecord(job.args) ? { ...job.args } : {}
  delete args.input
  delete args.out
  const taskIds = isRecord(job.taskIds) ? job.taskIds : null
  return {
    ...args,
    jobs: taskIds ? Object.keys(taskIds).map((k) => k.replace(/JobHash$/, '')) : null,
    // Newer bridge jobs also record the routes and MVSEP options they sent.
    ...(job.routes !== undefined ? { routes: job.routes } : {}),
    ...(job.options !== undefined ? { options: job.options } : {})
  }
}

/** A stem's recipe from its row, for stems made before recipes existed. */
export function deriveStemRecipe(row: StemRowForRecipe): Recipe {
  const createdAt = row.createdAt ?? 0
  if (row.table === 'stem_sets') {
    const imported = row.origin === 'import'
    const fromJob = imported && isRecord(row.job)
    const r = localRecipe({
      operation: imported ? 'stem-import' : 'stem-set',
      recordedBy: 'app',
      provider: fromJob ? 'mvsep' : undefined,
      fromAssetId: row.assetId,
      inputs: row.sourcePath ? [{ role: 'upload', path: row.sourcePath }] : [],
      settings: fromJob ? splitJobSettings(row.job) : {},
      credits: fromJob ? { provider: 'local', amount: 0, unit: 'none', basis: 'none' } : undefined,
      createdAt
    })
    return { ...r, recordedBy: 'backfill', missing: imported && !fromJob ? ['the split route that made the files'] : [] }
  }
  if (row.table === 'project_stems' && row.origin === 'imported') {
    const r = localRecipe({ operation: 'stem-import', recordedBy: 'app', fromAssetId: row.assetId, settings: { stem: row.stemKey ?? null }, createdAt })
    return { ...r, recordedBy: 'backfill', missing: ['the original file path'] }
  }
  const operation: RecipeOperation = row.table === 'extraction_stems' ? 'extract' : 'split'
  const synthesized = row.origin === 'synthesized'
  const r = localRecipe({
    operation,
    recordedBy: 'app',
    provider: synthesized ? 'local' : 'mvsep',
    fromAssetId: row.assetId,
    settings: { stem: row.stemKey ?? null, ...(synthesized ? { derived: 'computed locally from the other stems' } : {}) },
    credits: synthesized ? { provider: 'local', amount: 0, unit: 'none', basis: 'none' } : undefined,
    createdAt
  })
  return { ...r, recordedBy: 'backfill', missing: synthesized ? [] : ['the separation route and model'] }
}

// ── Reusing one ─────────────────────────────────────────────────────────────

const SUNO_OPERATIONS: RecipeOperation[] = ['generate', 'sounds', 'cover', 'add-vocals', 'add-instrumental', 'extend', 'replace-section', 'mashup']

export function isPromptRecipe(r: Recipe | null): boolean {
  return !!r && SUNO_OPERATIONS.includes(r.operation)
}

/** Why Reuse cannot run on this recipe, or null when it can. */
export function recipeRefusal(r: Recipe | null): string | null {
  if (!r) return 'No recipe was recorded'
  if (isPromptRecipe(r)) return null
  if (r.operation === 'import' || r.operation === 'stem-import') return 'Imported, so no prompt was recorded'
  return 'Made from another asset: reuse the one it came from'
}

/** The composer's fields, by the names GeneratePanel holds them. */
export interface ComposerFields {
  tab: 'song' | 'remix' | 'sounds'
  remixVerb: 'cover' | 'addVocals' | 'addInstrumental'
  customMode: boolean
  prompt: string
  style: string
  title: string
  model: string
  instrumental: boolean
  vocalGender: 'male' | 'female' | null
  negativeTags: string
  styleWeight: number
  weirdness: number
  sourceAssetId: string
  sourcePath: string
  audioWeight: number
  soundKey: string
  soundTempo: string
  soundLoop: boolean
  /** Seconds as typed; '' is the model's own length. */
  duration: string
  /** Suno's Variety 0..4; null sends nothing (the provider's default). */
  variety: number | null
  /** Sounds: capture lyric subtitles. */
  grabLyrics: boolean
}

export interface ReusePlan {
  /** The fields to load; anything absent keeps the composer's value. */
  fields: Partial<ComposerFields>
  /** One line each for what did not come back. */
  notes: string[]
  /** The MCP operation that makes the same thing again, and its arguments. */
  call: { op: string; args: Record<string, unknown> } | null
}

/** Recipe settings Create restores; any other recorded setting is named in a note. */
const COMPOSER_SETTINGS = new Set([
  'negativeTags', 'styleWeight', 'weirdnessConstraint', 'audioWeight', 'vocalGender',
  'soundKey', 'soundTempo', 'soundLoop', 'key', 'tempo', 'loop', 'duration', 'variety', 'grabLyrics'
])

/** Operations the MCP stored as `op` before recipes existed. */
const LEGACY_OPS = ['generate', 'sounds', 'cover', 'add_vocals', 'add_instrumental', 'extend', 'replace_section', 'mashup']

function num(v: unknown): number | undefined {
  return typeof v === 'number' && Number.isFinite(v) ? v : undefined
}

const MCP_OP: Partial<Record<RecipeOperation, string>> = {
  generate: 'aurora_generate',
  sounds: 'aurora_sounds',
  cover: 'aurora_cover',
  'add-vocals': 'aurora_add_vocals',
  'add-instrumental': 'aurora_add_instrumental',
  extend: 'aurora_extend',
  'replace-section': 'aurora_replace_section',
  mashup: 'aurora_mashup'
}

/**
 * What Reuse loads. `withReference` keeps the source audio a transform worked
 * on; without it a transform comes back as a song made from the same words.
 * `knownModels` is the composer's model list: a model no longer offered falls
 * back to `fallbackModel`, said in a note.
 */
export function reusePlan(r: Recipe, opts: { withReference: boolean; knownModels: readonly string[]; fallbackModel: string }): ReusePlan {
  const s = r.settings
  const notes: string[] = []
  // Wire ids use underscores (V5_5) where the composer lists dots (V5.5): match either.
  const wire = (m: string): string => m.replace(/\./g, '_').toUpperCase()
  const known = r.model ? opts.knownModels.find((m) => wire(m) === wire(r.model!)) : undefined
  const model = known ?? opts.fallbackModel
  if (!known) notes.push(`Made on ${r.model ?? 'an unrecorded model'}, which the composer no longer offers: set up for ${opts.fallbackModel}.`)
  const sourceId = r.inputs.find((i) => i.role === 'source')?.assetId ?? ''
  const sourcePath = r.inputs.find((i) => i.role === 'upload')?.path ?? ''
  const hasSource = !!(sourceId || sourcePath)
  const fields: Partial<ComposerFields> = {
    model,
    prompt: r.prompt ?? '',
    style: r.style ?? '',
    title: r.title ?? '',
    instrumental: r.instrumental ?? false,
    customMode: r.customMode ?? true,
    vocalGender: (s.vocalGender as ComposerFields['vocalGender']) ?? null,
    negativeTags: typeof s.negativeTags === 'string' ? s.negativeTags : '',
    // Always set, so a load never inherits the last recipe's length or variety.
    duration: num(s.duration) !== undefined ? String(s.duration) : '',
    variety: num(s.variety) ?? null,
    grabLyrics: s.grabLyrics === true
  }
  const sw = num(s.styleWeight)
  const wc = num(s.weirdnessConstraint)
  const aw = num(s.audioWeight)
  if (sw !== undefined) fields.styleWeight = sw
  if (wc !== undefined) fields.weirdness = wc
  if (aw !== undefined) fields.audioWeight = aw

  if (r.operation === 'sounds') {
    fields.tab = 'sounds'
    // The app stores soundKey/soundTempo/soundLoop; the MCP's sounds op takes key/tempo/loop.
    const key = s.soundKey ?? s.key
    const tempo = num(s.soundTempo) ?? num(s.tempo)
    fields.soundKey = typeof key === 'string' ? key : 'Any'
    fields.soundTempo = tempo !== undefined ? String(tempo) : ''
    fields.soundLoop = (s.soundLoop ?? s.loop) === true
  } else if (r.operation === 'cover' || r.operation === 'add-vocals' || r.operation === 'add-instrumental') {
    const verb = r.operation === 'cover' ? 'cover' : r.operation === 'add-vocals' ? 'addVocals' : 'addInstrumental'
    if (opts.withReference && hasSource) {
      fields.tab = 'remix'
      fields.remixVerb = verb
      fields.sourceAssetId = sourceId ?? ''
      fields.sourcePath = sourceId ? '' : sourcePath ?? ''
    } else {
      fields.tab = 'song'
      if (opts.withReference) notes.push('The source audio was not recorded: set up as a song from the same words.')
    }
  } else {
    fields.tab = 'song'
    if (r.operation !== 'generate') notes.push(`The composer has no ${r.operation} control: set up as a song from the same words.`)
  }
  // Settings Create has no control for are named, so a reuse never looks complete when it is not.
  const lost = Object.keys(s).filter((k) => !COMPOSER_SETTINGS.has(k) && s[k] !== null && s[k] !== '')
  if (lost.length) notes.push(`Not restored, Create has no control for: ${lost.join(', ')}.`)

  const op = MCP_OP[r.operation]
  let call: ReusePlan['call'] = null
  if (op) {
    const args: Record<string, unknown> = { ...r.settings }
    for (const k of ['prompt', 'style', 'title', 'instrumental', 'customMode', 'model'] as const) {
      const v = r[k]
      if (v !== null && v !== undefined) args[k] = v
    }
    if (r.operation === 'add-instrumental' && r.style) {
      args.tags = r.style
      delete args.style
    }
    if (hasSource && (opts.withReference || r.operation === 'cover' || r.operation === 'add-vocals' || r.operation === 'add-instrumental' || r.operation === 'extend' || r.operation === 'replace-section' || r.operation === 'mashup')) {
      if (sourceId) args.sourceAssetId = sourceId
      else if (sourcePath) args.sourcePath = sourcePath
    }
    const b = r.inputs.find((i) => i.role === 'mashup-b')
    if (b?.assetId) args.sourceAssetIdB = b.assetId
    else if (b?.path) args.sourcePathB = b.path
    if (!opts.withReference && r.operation !== 'generate' && r.operation !== 'sounds') {
      call = { op: 'aurora_generate', args: stripTransformArgs(args) }
    } else {
      call = { op, args }
    }
  }
  return { fields, notes, call }
}

function stripTransformArgs(args: Record<string, unknown>): Record<string, unknown> {
  const out = { ...args }
  for (const k of ['sourceAssetId', 'sourcePath', 'sourceAssetIdB', 'sourcePathB', 'audioWeight', 'continueAt', 'infillStartS', 'infillEndS', 'defaultParamFlag', 'tags']) delete out[k]
  return out
}

// ── Copying one out ─────────────────────────────────────────────────────────

const OPERATION_LABEL: Record<RecipeOperation, string> = {
  generate: 'Song',
  sounds: 'Sound',
  cover: 'Cover',
  'add-vocals': 'Add vocals',
  'add-instrumental': 'Add instrumental',
  extend: 'Extend',
  'replace-section': 'Replace section',
  mashup: 'Mashup',
  import: 'Import',
  master: 'Master',
  split: 'Split',
  extract: 'Extraction',
  'stem-import': 'Imported stems',
  'stem-set': 'Stem set',
  'pitch-shift': 'Pitch shift',
  convert: 'Conversion',
  unknown: 'Unknown'
}

export function operationLabel(op: RecipeOperation): string {
  return OPERATION_LABEL[op] ?? op
}

const RELATION_LABEL: Record<RecipeLineage['relation'], string> = {
  'cover-of': 'Cover of',
  'layered-on': 'Layered on',
  'extended-from': 'Extended from',
  'edited-from': 'Edited from',
  'mashup-of': 'Mashup of',
  'split-from': 'Split from',
  'extracted-from': 'Extracted from',
  'mastered-from': 'Mastered from',
  'stems-of': 'Stems of',
  'derived-from': 'Made from'
}

export function relationLabel(rel: RecipeLineage['relation']): string {
  return RELATION_LABEL[rel] ?? rel
}

export function creditsLabel(c: RecipeCredits | null | undefined): string {
  if (!c) return 'Not recorded'
  if (c.basis === 'none') return 'Free (local)'
  if (c.amount === null) return c.unit === 'mvsep-minutes' ? 'MVSEP premium minutes, amount not recorded' : 'Suno credits, amount not measured'
  const unit = c.unit === 'mvsep-minutes' ? 'premium minutes' : 'Suno credits'
  return `${c.amount} ${unit}${c.basis === 'estimate' ? ' (estimate)' : ''}`
}

function settingValue(v: unknown): string {
  if (v === null || v === undefined) return '—'
  if (typeof v === 'object') return JSON.stringify(v)
  return String(v)
}

/** The whole recipe as readable text: what Copy recipe puts on the clipboard. */
export function recipeText(r: Recipe, nameOf: (assetId: string) => string | null = () => null): string {
  const lines: string[] = [`${operationLabel(r.operation)}${r.model ? ` · ${r.model}` : ''}${r.provider && r.provider !== 'local' ? ` · ${r.provider}` : ''}`]
  if (r.title) lines.push(`Title: ${r.title}`)
  if (r.style) lines.push(`Style: ${r.style}`)
  if (r.prompt) lines.push(`${r.customMode === false ? 'Description' : 'Lyrics'}:\n${r.prompt}`)
  if (r.instrumental) lines.push('Instrumental')
  const settings = Object.entries(r.settings)
  if (settings.length) lines.push('Settings: ' + settings.map(([k, v]) => `${k} ${settingValue(v)}`).join(' · '))
  for (const i of r.inputs) lines.push(`Input (${i.role}): ${(i.assetId && nameOf(i.assetId)) || i.name || i.path || i.assetId}`)
  for (const l of r.lineage) lines.push(`${relationLabel(l.relation)}: ${nameOf(l.assetId) ?? l.assetId}`)
  lines.push(`Cost: ${creditsLabel(r.credits)}`)
  if (r.createdAt) lines.push(`Made: ${new Date(r.createdAt).toISOString().replace('T', ' ').slice(0, 16)}`)
  if (r.missing?.length) lines.push(`Not recorded: ${r.missing.join('; ')}`)
  return lines.join('\n')
}

/** Follow lineage back to the nearest recipe that can be reused (a master or a
 *  stem reuses the generation it came from). `recipeOf` resolves an asset id. */
export function reusableAncestor(r: Recipe | null, recipeOf: (assetId: string) => Recipe | null, maxHops = 8): { recipe: Recipe; assetId: string | null } | null {
  if (r && isPromptRecipe(r)) return { recipe: r, assetId: null }
  let cur = r
  for (let hop = 0; cur && hop < maxHops; hop++) {
    const parent = cur.lineage[0]?.assetId
    if (!parent) return null
    const next = recipeOf(parent)
    if (next && isPromptRecipe(next)) return { recipe: next, assetId: parent }
    cur = next
  }
  return null
}
